export type SectionType = {
  title: string;
  id: string;
  subSecIds: string[];
}

export type SubSectionType = {
  id: string;
  title: string;
  activityIds: OrderType;
}

export type ActivityType = {
  author: string;
  eventDate: string;
  uid: string;
  imgCaption: string;
  title: string;
  approved: boolean;
  brochureUrl: string;
  imgUrl: string[];
  id: string;
  createdInSeconds: number;
  created: string;
  categoryId: string;
  content: string;
}

type OrderType = string[]

export type DndType = {
  sections: Record<SectionType['id'], SectionType>;
  subSections: Record<SubSectionType['id'], SubSectionType>;
  activities: Record<ActivityType['id'], ActivityType>;
  sectionOrder: OrderType;
}

export const data: DndType = {
  "sections": {
    "s6": {
      "title": "Upcoming Events",
      "id": "s6",
      "subSecIds": []
    },
    "s3": {
      "id": "s3",
      "title": "Awards",
      "subSecIds": []
    },
    "s0": {
      "title": "Academic Activities",
      "subSecIds": [],
      "id": "s0"
    },
    "default": {
      "id": "default",
      "subSecIds": [
        "12",
        "6",
        "7",
        "15",
        "9",
        "14",
        "10",
        "16",
        "1",
        "13",
        "3",
        "11",
        "2"
      ],
      "title": "All activities"
    },
    "s4": {
      "subSecIds": [],
      "title": "Outreach Activities",
      "id": "s4"
    },
    "s1": {
      "id": "s1",
      "title": "Research & Development",
      "subSecIds": []
    },
    "s5": {
      "title": "Alumni Association",
      "id": "s5",
      "subSecIds": []
    },
    "s2": {
      "id": "s2",
      "subSecIds": [],
      "title": "Faculty Empowerment Programs"
    }
  },
  "sectionOrder": [
    "default",
    "s0",
    "s1",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6"
  ],
  "activities": {
    "VT5xmCoMxZ39vBqLIROI": {
      "author": "Sahadev Roy",
      "eventDate": "2024-11-11",
      "uid": "zyYjfIjQ01XNIjOVxu9UPh0HfKC2",
      "imgCaption": "Session Chair of 3rd International Conference on the Paradigm Shifts in Communication, Embedded Systems, Machine Learning and Signal Processing 2024, VNIT Nagpur",
      "title": "",
      "approved": true,
      "brochureUrl": "",
      "imgUrl": [],
      "id": "VT5xmCoMxZ39vBqLIROI",
      "createdInSeconds": 1734715836527,
      "created": "20 Dec 2024, 11:00 pm",
      "categoryId": "9",
      "content": "Chatterjee, Sudipta. *Multiple Controls Wheelchair for Elderly People & Lower Limb Disabilities for Hilly Region * [Paper presentation]. 3rd International Conference on the Paradigm Shifts in Communication, Embedded Systems, Machine Learning and Signal Processing 2024, VNIT Nagpur, from 2024-11-11 to 2024-11-12. "
    },
    "F6LQOiN685uoJNONUjUi": {
      "brochureUrl": "",
      "uid": "xnoizenzToUmYoJ1Ij4WKVnDrlI2",
      "created": "22 Dec 2024, 3:28 pm",
      "imgUrl": [],
      "eventDate": "2024-11-28",
      "createdInSeconds": 1734861532212,
      "approved": true,
      "imgCaption": "",
      "content": "Dr. Haridharan M K, Assistant Professor, Department of Civil Engineering, NIT-Arunachal Pradesh, delivered a keynote lecture on 'Bridge Design' during the Training Programme on Cross Drainage Structures in Rural Roads (Nov 25-29, 2024). This NRIDA-sponsored program, hosted by NIT-Tiruchirappalli, targeted engineers and officials involved in PMGSY road construction.\"",
      "categoryId": "3",
      "title": "",
      "id": "F6LQOiN685uoJNONUjUi",
      "author": "Haridharan M K"
    },
    "UcAgXQl5D5veSzz2Brdj": {
      "created": "24 Nov 2024, 7:06 pm",
      "id": "UcAgXQl5D5veSzz2Brdj",
      "content": "A. Vanav Kumar, Associate Professor, Department of Basic and Applied Science served as a *Reviewer* of \"Applied Science\". MDPI. 2024-11-20.",
      "imgUrl": [],
      "author": "A Vanav Kumar",
      "approved": true,
      "categoryId": "12",
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "createdInSeconds": 1732455370153,
      "brochureUrl": "",
      "title": "",
      "eventDate": "2024-11-20",
      "imgCaption": ""
    },
    "ne91OKE0Vd4Ir0yOheTi": {
      "title": "",
      "eventDate": "2024-12-12",
      "createdInSeconds": 1735377300425,
      "content": "Lal Das, Bhaskar.Kant Pushpam, Hemant. *HarmonyAI* [Paper presentation].  International Conference on Emerging Trends in Business Analytics & Management Sciences,  Shailesh J. Mehta School of Management, IIT Bombay, from 2024-12-12 to 2024-12-14. ",
      "author": "A Vanav Kumar",
      "brochureUrl": "",
      "imgCaption": "",
      "created": "28 Dec 2024, 2:45 pm",
      "approved": true,
      "imgUrl": [],
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "id": "ne91OKE0Vd4Ir0yOheTi",
      "categoryId": "9"
    },
    "yOe2AZ5QjlL9I1IgOSt6": {
      "eventDate": "2024-12-13",
      "categoryId": "12",
      "brochureUrl": "",
      "title": "",
      "imgUrl": [],
      "id": "yOe2AZ5QjlL9I1IgOSt6",
      "author": "Nabakumar Pramanik",
      "approved": true,
      "created": "26-Dec-2024, 1:58 pm",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, BAS served as a *Reviewer* of \"Thesis/dissertation entitled Isolation, Characterization, And Applications of Manganese Peroxidase from Indigenous Fungi\". NERIST, Arunachal Pradesh. 2024-12-13.",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "createdInSeconds": 1735201721769,
      "imgCaption": ""
    },
    "bC9FWQaJh1iFuHBt00Lj": {
      "title": "",
      "created": "24 Dec 2024, 2:43 pm",
      "categoryId": "7",
      "brochureUrl": "",
      "imgCaption": "",
      "uid": "PXEZ4Wa6j7bP7yapvzHhR4VwGEE3",
      "author": "Ravi Ranjan",
      "createdInSeconds": 1735031606798,
      "approved": true,
      "id": "bC9FWQaJh1iFuHBt00Lj",
      "content": "Kumar, R. R.. (2024). Stochastic dynamic analysis of porous functionally graded plate: A multivariate adaptive regression splines approach. *Structural Engineering and Mechanics, An International Journal* *92*(3), 227-243. https://doi.org/10.12989/sem.2024.92.3.227",
      "imgUrl": [],
      "eventDate": ""
    },
    "xaMEUaqmsCpUQkKWlULx": {
      "created": "22 Dec 2024, 5:27 pm",
      "categoryId": "9",
      "title": "",
      "author": "Haridharan M K",
      "content": "Ravikant, Singh .G, Murali.R. , Bharathi Murugan. *Numerical investigation of cold-formed steel oval hollow section (OHS) compression members * [Paper presentation]. 14th Structural Engineering Convention ( An International Conference) , National Institute of Technology, Tiruchirappalli, from 2024-12-12 to 2024-12-14. ",
      "imgUrl": [],
      "approved": true,
      "id": "xaMEUaqmsCpUQkKWlULx",
      "imgCaption": "",
      "eventDate": "2024-12-12",
      "uid": "xnoizenzToUmYoJ1Ij4WKVnDrlI2",
      "createdInSeconds": 1734868622890,
      "brochureUrl": ""
    },
    "bfRLJwOnxu3gSggvFngg": {
      "created": "20 Dec 2024, 11:02 pm",
      "author": "Sahadev Roy",
      "content": "Dr. Sahadev Roy, Assistant Professor , ECE was *The Chair of Panel Session* at 3rd International Conference on the Paradigm Shifts in Communication, Embedded Systems, Machine Learning and Signal Processing 2024, organised by VNIT Nagpur, from 2024-11-11 to 2024-11-12.",
      "categoryId": "13",
      "imgCaption": "Session Chair of 3rd International Conference on the Paradigm Shifts in Communication, Embedded Systems, Machine Learning and Signal Processing 2024",
      "brochureUrl": "",
      "id": "bfRLJwOnxu3gSggvFngg",
      "title": "",
      "imgUrl": [],
      "eventDate": "2024-11-11",
      "uid": "zyYjfIjQ01XNIjOVxu9UPh0HfKC2",
      "createdInSeconds": 1734715977107,
      "approved": true
    },
    "V7Oq3DBQCwR2JWCMBvBj": {
      "imgCaption": "",
      "createdInSeconds": 1735200958713,
      "title": "",
      "categoryId": "13",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "id": "V7Oq3DBQCwR2JWCMBvBj",
      "approved": true,
      "author": "Nabakumar Pramanik",
      "brochureUrl": "",
      "created": "26-Dec-2024, 1:45 pm",
      "eventDate": "2024-11-25",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, BAS was *The Chair of Panel Session* at one-day Workshop on “Research opportunities in DRDO through ARMREB”, organised by IIT Guwahati, from 2024-11-25 to 2024-11-25.",
      "imgUrl": []
    },
    "OSOlt7yOPAS5kswWJXJp": {
      "author": "A Vanav Kumar",
      "brochureUrl": "",
      "createdInSeconds": 1735376403454,
      "eventDate": "2024-12-31",
      "created": "28 Dec 2024, 2:30 pm",
      "imgCaption": "",
      "title": "",
      "content": "A. Vanav Kumar, Associate Professor, Department of Basic and Applied Science served as a *Reviewer* of \"Axiom\". MDPI. 2024-12-31.",
      "approved": true,
      "categoryId": "12",
      "id": "OSOlt7yOPAS5kswWJXJp",
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "imgUrl": []
    },
    "ZpJypUARBctvckdQpPt7": {
      "imgUrl": [],
      "brochureUrl": "",
      "title": "",
      "author": "A Vanav Kumar",
      "id": "ZpJypUARBctvckdQpPt7",
      "eventDate": "2024-12-12",
      "createdInSeconds": 1735132200934,
      "categoryId": "9",
      "created": "25 Dec 2024, 6:40 pm",
      "approved": true,
      "imgCaption": "",
      "content": "AUTHOR(S) *Image enhancement through Stable Diffusion method* [Paper presentation]. International Conference on Applied Mathematical Sciences for Emerging Technologies – 2024, Department of Mathematics, School of Engineering and Technology,Dhanalakshmi Srinivasan University, Perambalur, Tamil Nadu, India and jointly organised with SIIRT University,Turkey, from 2024-12-12 to 2024-12-13. ",
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2"
    },
    "3zyDWtvs6U1VyqRGiRis": {
      "id": "3zyDWtvs6U1VyqRGiRis",
      "createdInSeconds": 1736487406859,
      "categoryId": "16",
      "imgCaption": "Constitution Day Celebration ",
      "uid": "1meMTeaYftWPu0KVhmKhjj8h9Fu1",
      "brochureUrl": "",
      "eventDate": "2024-11-26",
      "author": "Vijayakumar Kathirvel",
      "content": "Constitution Day Celebration  was organised  by Dr. K. Vijayakumar, Assistant Professor, Dept of Management and Humanities to commemorate the adoption of Constitutions of India, The celebration began at 9:00 AM with a gathering of faculty members and staff in the corridor near the Registrar's office. Dr. Rajen Pudur, the Registrar of NITAP, presided over the ceremony and led the pledge-taking session. The Constitution Day pledge was also administered in all the examination halls, both in the morning and afternoon sessions, ensuring that every student and invigilator participated in this significant event. Through these actions, NITAP reinforced the importance of the Constitution and its values, promoting awareness and instilling a sense of respect for the Indian Constitution among the academic community. This celebration highlighted the institute's commitment to upholding democratic principles and reinforcing the significance of the Constitution in shaping the nation's identity. on 2024-11-26.",
      "imgUrl": [],
      "created": "10 Jan 2025, 11:06 am",
      "approved": true,
      "title": ""
    },
    "VjoIm4R6jk3cYqDi0hV9": {
      "imgCaption": "",
      "eventDate": "2024-12-12",
      "imgUrl": [],
      "id": "VjoIm4R6jk3cYqDi0hV9",
      "uid": "xnoizenzToUmYoJ1Ij4WKVnDrlI2",
      "createdInSeconds": 1734868792553,
      "created": "22 Dec 2024, 5:29 pm",
      "content": "Dr.Haridharan M .K. et.al presented a paper on “Numerical investigation of cold-formed steel oval hollow section (OHS) compression members” in 14th Structural Engineering Convention (An International Conference) at National Institute of Technology, Tiruchirappalli, from 2024-12-12 to 2024-12-14.",
      "brochureUrl": "",
      "author": "Haridharan M K",
      "categoryId": "9",
      "title": "",
      "approved": true
    },
    "Kg5zVsGUeYa1Q0VPIlw5": {
      "brochureUrl": "",
      "author": "Haridharan M K",
      "content": "Dr Haridharan M K, Assistant Professor, Department of Civil Engineering was Session Chair for the session on “Soil-Structure Interaction/Machine Foundation” theme in  14th Structural Engineering Convention (An International Conference), organized by National Institute of Technology, Tiruchirappalli , from 2024-12-12 to 2024-12-14",
      "imgCaption": "",
      "eventDate": "2024-12-12",
      "created": "22 Dec 2024, 5:16 pm",
      "title": "",
      "categoryId": "13",
      "id": "Kg5zVsGUeYa1Q0VPIlw5",
      "imgUrl": [],
      "uid": "xnoizenzToUmYoJ1Ij4WKVnDrlI2",
      "approved": true,
      "createdInSeconds": 1734868006361
    },
    "8JzNhtuMCdEynrOVBCrc": {
      "created": "26-Dec-2024, 1:29 pm",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, BAS, participated in Industry Academia Conclave-2024 was organised  by NIT, Jamshedpur  on the Industrial activities, from 2024-11-15 to 2024-11-17.",
      "imgUrl": [],
      "createdInSeconds": 1735199984784,
      "title": "",
      "brochureUrl": "",
      "author": "Nabakumar Pramanik",
      "approved": true,
      "imgCaption": "",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "id": "8JzNhtuMCdEynrOVBCrc",
      "categoryId": "16",
      "eventDate": "2024-11-15"
    },
    "T077O07glXBSWviEPyyC": {
      "createdInSeconds": 1735376811967,
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "categoryId": "11",
      "title": "",
      "author": "A Vanav Kumar",
      "eventDate": "2024-12-16",
      "created": "28 Dec 2024, 2:36 pm",
      "brochureUrl": "",
      "content": "A. Vanav Kumar, Associate Professor, Basic and Applied Science attended Workshop on \"HydromasteR\", organised by IIT, Hyderabad, from 2024-12-16 to 2024-12-20.",
      "id": "T077O07glXBSWviEPyyC",
      "imgUrl": [],
      "imgCaption": "",
      "approved": true
    },
    "4Aad1bWBNFOSlFG8vWjt": {
      "id": "4Aad1bWBNFOSlFG8vWjt",
      "author": "Haridharan M K",
      "imgUrl": [],
      "categoryId": "12",
      "brochureUrl": "",
      "created": "30 Dec 2024, 8:50 am",
      "eventDate": "2024-11-20",
      "title": "",
      "uid": "xnoizenzToUmYoJ1Ij4WKVnDrlI2",
      "content": "Dr Haridharan M K, Assistant Professor, Department of Civil Engineering Served as Reviewer in 14th Structural Engineering Convention (An International Conference), organized by National Institute of Technology, Tiruchirappalli , from 2024-12-12 to 2024-12-14.",
      "createdInSeconds": 1735528816200,
      "imgCaption": "",
      "approved": true
    },
    "aScp7zNAZIY01906NX6s": {
      "eventDate": "2024-11-19",
      "title": "",
      "imgUrl": [],
      "id": "aScp7zNAZIY01906NX6s",
      "createdInSeconds": 1735376654287,
      "approved": true,
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "created": "28 Dec 2024, 2:34 pm",
      "author": "A Vanav Kumar",
      "categoryId": "11",
      "brochureUrl": "",
      "content": "A. Vanav Kumar, Associate Professor, Department of Basic and Applied Science attended Industrial Training on \"Generative AI and its Applcations\", organised by Eduxlabs and Mechanica, IIT, Madras, from 2024-11-19 to 2024-12-04.",
      "imgCaption": ""
    },
    "GxxZvRLItT45Hg5E5hI7": {
      "imgCaption": "",
      "approved": true,
      "eventDate": "2024-11-10",
      "imgUrl": [],
      "content": "A. Vanav Kumar, Associate Professor, Basic and Applied Science served as a *Reviewer* of \"Applied Science\". MDPI. 2024-11-10.",
      "createdInSeconds": 1735376295311,
      "author": "A Vanav Kumar",
      "title": "",
      "categoryId": "12",
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "brochureUrl": "",
      "created": "28 Dec 2024, 2:28 pm",
      "id": "GxxZvRLItT45Hg5E5hI7"
    },
    "IoW107QPNJrDzDVQCQKm": {
      "imgUrl": [],
      "createdInSeconds": 1734893243655,
      "approved": true,
      "imgCaption": "",
      "content": "M.K.Haridharan et.al. \"Optimizing Lime Mortar Performance: A Comprehensive Study on Mechanical and Durability Improvements with Palm Jaggery and Gallnuts.\" JOM- The Minerals, Metals & Material Society, Vol: 76 Issue (12), 7168 - 7185. https://doi.org/10.1007/s11837-024-06903-w",
      "id": "IoW107QPNJrDzDVQCQKm",
      "brochureUrl": "",
      "created": "23 Dec 2024, 12:17 am",
      "categoryId": "7",
      "eventDate": "",
      "uid": "xnoizenzToUmYoJ1Ij4WKVnDrlI2",
      "author": "Haridharan M K",
      "title": ""
    },
    "dUeSZxsHvvweM0zGAyLq": {
      "categoryId": "11",
      "created": "24 Nov 2024, 7:11 pm",
      "content": "A. Vanav Kumar, Associate Professor, Department of Basic and Applied Science attended FDP on \"Elsevier Higher Education & Research Excellence Forum\", organised by Elsevier publishing Unit, from 2024-11-19 to 2024-11-19.",
      "imgCaption": "Session on Generative AI, Elsevier Higher Education & Research Excellence Forum, 19, November 2024",
      "brochureUrl": "",
      "title": "",
      "imgUrl": [],
      "eventDate": "2024-11-19",
      "approved": true,
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "createdInSeconds": 1732455682330,
      "id": "dUeSZxsHvvweM0zGAyLq",
      "author": "A Vanav Kumar"
    },
    "YKTAjpym00GiZBiG5HCl": {
      "approved": true,
      "created": "22 Dec 2024, 5:23 pm",
      "author": "Haridharan M K",
      "categoryId": "2",
      "id": "YKTAjpym00GiZBiG5HCl",
      "title": "",
      "brochureUrl": "",
      "createdInSeconds": 1734868381121,
      "eventDate": "2024-11-29",
      "uid": "xnoizenzToUmYoJ1Ij4WKVnDrlI2",
      "imgUrl": [],
      "content": "Dr. Haridharan M K, Assistant Professor, Department of Civil Engineering, NIT-Arunachal Pradesh, delivered a keynote lecture on “Construction Aspects of Bridges” during the Training Programme on Cross Drainage Structures in Rural Roads (NRIDA) (Nov 25-29, 2024). This NRIDA-sponsored program, hosted by NIT-Tiruchirappalli, targeted engineers and officials involved in PMGSY road construction.",
      "imgCaption": ""
    },
    "3rGPreNFQSZrEQKYHgOx": {
      "title": "",
      "categoryId": "16",
      "approved": true,
      "imgCaption": "",
      "id": "3rGPreNFQSZrEQKYHgOx",
      "author": "Nabakumar Pramanik",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, BAS, Participated in the Outreach Activity, on “Research opportunities in DRDO through ARMREB” was organised  by IIT, Guwahati  on the Project activities, from 2024-11-25 to 2024-11-25.",
      "brochureUrl": "",
      "created": "26-Dec-2024, 1:41 pm",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "eventDate": "2024-11-25",
      "createdInSeconds": 1735200669441,
      "imgUrl": []
    },
    "hlGPiuzkGKjdFanqbel9": {
      "brochureUrl": "",
      "created": "1 Mar 2025, 7:47 pm",
      "title": "",
      "approved": true,
      "author": "Sahadev Roy",
      "createdInSeconds": 1740838667603,
      "eventDate": "2025-03-01",
      "categoryId": "12",
      "uid": "zyYjfIjQ01XNIjOVxu9UPh0HfKC2",
      "imgCaption": "",
      "imgUrl": [],
      "id": "hlGPiuzkGKjdFanqbel9",
      "content": "Dr, Sahadev Roy, Assistant Professor, ECE served as a *Reviewer* of \"Current Applied Physics\". Elsevier. 2025-03-01."
    },
    "76qWVFxriWGPOZv37qVG": {
      "imgCaption": "",
      "createdInSeconds": 1742302410279,
      "title": "",
      "categoryId": "12",
      "uid": "zyYjfIjQ01XNIjOVxu9UPh0HfKC2",
      "created": "18-Mar-2025, 6:23 pm",
      "approved": true,
      "imgUrl": [],
      "brochureUrl": "",
      "eventDate": "2025-03-18",
      "author": "Sahadev Roy",
      "id": "76qWVFxriWGPOZv37qVG",
      "content": "Dr. Sahadev Roy, Assistant Professor, Department of ECE served as a *Reviewer* of \"National Academy Science Letters\". Springer. 2025-03-18."
    },
    "NU1ITQdp1OXnHHhweteZ": {
      "categoryId": "12",
      "imgUrl": [],
      "imgCaption": "3rd International Conference on Intelligent Systems, Advanced Computing, and Communication (ISACC 2025). ",
      "author": "Sahadev Roy",
      "created": "25 Mar 2025, 8:52 pm",
      "uid": "zyYjfIjQ01XNIjOVxu9UPh0HfKC2",
      "createdInSeconds": 1742916157848,
      "approved": true,
      "brochureUrl": "",
      "eventDate": "2025-03-25",
      "title": "",
      "id": "NU1ITQdp1OXnHHhweteZ",
      "content": "Dr. Sahadev Roy, Assistant Professor, Dept. of ECE served as a *Reviewer* of \"3rd international conference on intelligent systems advanced computing and communication Assam University\". IEEE. 2025-03-25."
    },
    "9CqWdNqfXUvHMnTF0VuQ": {
      "eventDate": "",
      "title": "",
      "createdInSeconds": 1744785110641,
      "uid": "zyYjfIjQ01XNIjOVxu9UPh0HfKC2",
      "approved": true,
      "categoryId": "6",
      "author": "Sahadev Roy",
      "created": "16 Apr 2025, 12:01 pm",
      "brochureUrl": "",
      "imgUrl": [],
      "imgCaption": "Certificate",
      "id": "9CqWdNqfXUvHMnTF0VuQ",
      "content": "Aditya Roy & Dr. Sahadev Roy, \"Autonomes Unterwasserfahrzeug für Unterwasserdatenerfassung (Autonomous Underwater Vehicle for Underwater Data Collection)\". (2025). Patent ID 202025101227.8. German Utility Patent ."
    },
    "C5n9IvzZrShJYqPhbdyc": {
      "categoryId": "7",
      "imgCaption": "",
      "author": "Debjit Dutta",
      "createdInSeconds": 1745386100725,
      "created": "23-Apr-2025, 10:58 am",
      "approved": true,
      "eventDate": "",
      "title": "",
      "brochureUrl": "",
      "uid": "7N1NwJNwGfNjN8IwZsZ4fjhOrry2",
      "imgUrl": [],
      "id": "C5n9IvzZrShJYqPhbdyc",
      "content": "Pradhan, DEBPRASAD.Dutta, DEBJIT. (2025). Nonlinear excitation and bi-directional propagation of heavy-nucleus-acoustic waves in multi-component unmagnetized quantum plasmas. * Chaos, Solitons and Fractals *. Accpepted in April 11, 2025 (SCI, Category : Q1, Impact Factor: 5.7)"
    },
    "vf32dOPSIVtfukL4xiiP": {
      "createdInSeconds": 1745397174225,
      "author": "M Berlin",
      "created": "23-Apr-2025, 2:02 pm",
      "uid": "L3JwBJAHf5aQIyAwvljtNSKYV9z1",
      "brochureUrl": "",
      "approved": true,
      "imgUrl": [],
      "imgCaption": "",
      "eventDate": "",
      "categoryId": "7",
      "title": "",
      "id": "vf32dOPSIVtfukL4xiiP",
      "content": "Palpi Boruah, RADHA .Mohanadhas, BERLIN .Kamalanathan , JAYAKESH . (2025). A comparative study of the shear strength of a poorly graded soil using Bacillus subtilis, vetiver fibre and bamboo fibre. *Advances in Bamboo Science*. https://doi.org/10.1016/j.bamboo.2025.100146"
    },
    "bup9d1qro73Ql65Cmiu7": {
      "title": "",
      "created": "23-Apr-2025, 2:06 pm",
      "categoryId": "7",
      "brochureUrl": "",
      "createdInSeconds": 1745397368873,
      "imgCaption": "",
      "uid": "L3JwBJAHf5aQIyAwvljtNSKYV9z1",
      "eventDate": "",
      "approved": true,
      "author": "M Berlin",
      "imgUrl": [],
      "id": "bup9d1qro73Ql65Cmiu7",
      "content": "Jino , LAWRENCE.Natarajan , NARAYANAN.Berlin , MOHANADHAS.Alagarsamy , VANAV KUMAR.Swapnali , DOLEY.Vasudevan , MANGOTTRI . (2025). Temporal fractionation models for depicting mass transfer limiting conditions of multispecies transport in porous media. *Groundwater for Sustainable Development* *29*(101438). https://doi.org/10.1016/j.gsd.2025.101438"
    },
    "vDVpvrWDC8GfLKYgBZJS": {
      "eventDate": "",
      "uid": "L3JwBJAHf5aQIyAwvljtNSKYV9z1",
      "imgUrl": [],
      "brochureUrl": "",
      "author": "M Berlin",
      "title": "",
      "categoryId": "7",
      "approved": true,
      "createdInSeconds": 1745397483304,
      "imgCaption": "",
      "created": "23-Apr-2025, 2:08 pm",
      "id": "vDVpvrWDC8GfLKYgBZJS",
      "content": "Radha , PALPI BORUAH.Berlin , MOHANADHAS . (2025). Effect of Freezing and Thawing on Poorly Graded Sandy-Silt Soil. *Geomicrobiology Journal*. https://doi.org/10.1080/01490451.2025.2485468"
    },
    "ZrdhBGA2YaxjOZeWqViq": {
      "uid": "zyYjfIjQ01XNIjOVxu9UPh0HfKC2",
      "categoryId": "15",
      "imgUrl": [],
      "approved": true,
      "created": "24 Apr 2025, 1:21 pm",
      "imgCaption": "FDP Recent Trends in Embedded Systems Application in Mechatronics, Robotics, AI/ML, and Biomedical Engineering",
      "createdInSeconds": 1745481111668,
      "brochureUrl": "",
      "eventDate": "2025-03-24",
      "title": "",
      "author": "Sahadev Roy",
      "id": "ZrdhBGA2YaxjOZeWqViq",
      "content": " 5-Day Faculty Development Program (FDP)  on \"Recent Trends in Embedded Systems Application in Mechatronics, Robotics, AI/ML, and Biomedical Engineering\" was organized by Dr. Sahadev Roy Assistant Professor, Dept. of ECE,  at NIT Arunachal Pradesh, from 2025-03-24 to 2025-03-28."
    },
    "z7iVjJbODcKCzkrioQlY": {
      "brochureUrl": "",
      "eventDate": "2024-12-18",
      "categoryId": "9",
      "imgCaption": "",
      "title": "",
      "author": "Abhik Banerjee",
      "approved": true,
      "uid": "8ww8sD5XN3QlnYLLuUgqeAOMRwT2",
      "imgUrl": [],
      "created": "28 Apr 2025, 4:16 pm",
      "createdInSeconds": 1745837200734,
      "id": "z7iVjJbODcKCzkrioQlY",
      "content": "SACHIN, G M.ABHIK, BANERJEE.S N, DEEPA. *Optimal Reactive Power Control in Standalone Hybrid Power System by Using Harris Hawks Algorithm Tuned Statcom Tilt Controller* [Paper presentation]. 2024 IEEE International Conference on Power Electronics, Drives and Energy Systems (PEDES), NIT SURATHKAL, from 2024-12-18 to 2024-12-21. 10.1109/pedes61459.2024.10961278"
    },
    "RDYeVPDDquAQFl3HhPR1": {
      "brochureUrl": "",
      "title": "",
      "approved": true,
      "created": "28 Apr 2025, 4:19 pm",
      "createdInSeconds": 1745837385149,
      "author": "Abhik Banerjee",
      "uid": "8ww8sD5XN3QlnYLLuUgqeAOMRwT2",
      "eventDate": "2025-02-28",
      "categoryId": "9",
      "imgUrl": [],
      "imgCaption": "",
      "id": "RDYeVPDDquAQFl3HhPR1",
      "content": "SACHIN, G M.ABHIK, BANERJEE. *Reactive Power Compensation in Hybrid Power System using African Vulture Optimized Statcom Tilt Controller* [Paper presentation]. 2025 IEEE 1st International Conference on Smart and Sustainable Developments in Electrical Engineering (SSDEE), IIT DHANBAD, from 2025-02-28 to 2025-03-02. 10.1109/ssdee64538.2025.10968464"
    },
    "3UxlNWKfXTKU0D3mZ8Xu": {
      "createdInSeconds": 1745921768597,
      "approved": true,
      "uid": "zyYjfIjQ01XNIjOVxu9UPh0HfKC2",
      "title": "",
      "imgCaption": "Chess Champaion Leagues",
      "brochureUrl": "",
      "categoryId": "14",
      "author": "Sahadev Roy",
      "created": "29 Apr 2025, 3:46 pm",
      "eventDate": "2025-04-27",
      "imgUrl": [],
      "id": "3UxlNWKfXTKU0D3mZ8Xu",
      "content": "Dr. Sahadev Roy, Assistant Professor, Dept. of ECE, NIT Arunachal Pradesh won the 2nd  in the Chess on the theme of \"Champion League \" organized by Chess.com in association with International, 2025-04-27"
    },
    "S0tnvVYW05gjvMatzlUT": {
      "approved": true,
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "categoryId": "10",
      "author": "Nabakumar Pramanik",
      "title": "",
      "eventDate": "2025-03-09",
      "created": "1 May 2025, 10:20 am",
      "imgUrl": [],
      "imgCaption": "",
      "createdInSeconds": 1746075015984,
      "brochureUrl": "",
      "id": "S0tnvVYW05gjvMatzlUT",
      "content": "Das, A..Ghosh, S..Pramanik, N... (2025). Bioimaging Applications of Metal and Metal Oxide Nanoparticles. In Kalarikkal, N., Bhadrapriya, B.C., Anne Bose, B., Padmanabhan, P., Thomas, S., Vadakke Matham, M. (Eds.), *Multimodal Biomedical Imaging Techniques. Biological and Medical Physics, Biomedical Engineering* (pp. 181-214). Springer Nature. https://doi.org/10.1007/978-981-96-1124-9_8, ISBN: 978-981-96-1124-9"
    },
    "L8pzluz3a8NVkoobkPqx": {
      "createdInSeconds": 1746075647271,
      "brochureUrl": "",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "eventDate": "2025-03-03",
      "author": "Nabakumar Pramanik",
      "created": "1 May 2025, 10:30 am",
      "categoryId": "12",
      "approved": true,
      "title": "",
      "imgUrl": [],
      "imgCaption": "",
      "id": "L8pzluz3a8NVkoobkPqx",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, Basic and Applied Science served as a *Reviewer* of \"Design and development of responsive bio- based polymeric gel systems\". CSIR-National Institute for Interdisciplinary Science and Technology (CSIR-NIIST), Thiruvananthapuram, India. 2025-03-03."
    },
    "Z7XdEZJoKNPrfWPdDmA2": {
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "createdInSeconds": 1746075858518,
      "brochureUrl": "",
      "author": "Nabakumar Pramanik",
      "imgCaption": "",
      "eventDate": "2025-04-23",
      "approved": true,
      "title": "",
      "created": "1 May 2025, 10:34 am",
      "imgUrl": [],
      "categoryId": "12",
      "id": "Z7XdEZJoKNPrfWPdDmA2",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, Basic and Applied Science served as a *Reviewer* of \"Results in Chemistry\". Elsevier. 2025-04-23."
    },
    "EABXjZhJ0XiBHOXVMOsL": {
      "imgCaption": "",
      "categoryId": "16",
      "brochureUrl": "",
      "created": "1 May 2025, 10:51 am",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "title": "",
      "eventDate": "2025-04-29",
      "imgUrl": [],
      "approved": true,
      "createdInSeconds": 1746076912989,
      "author": "Nabakumar Pramanik",
      "id": "EABXjZhJ0XiBHOXVMOsL",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, Basic and Applied Science, participated in Conclave in collaboration with Wadhwani Foundation  was organised  by Wadhwani Foundation, Bharat Mandapam, New Delhi, India  on the Research and Development, from 2025-04-29 to 2025-04-29."
    },
    "6o2v6oRuDOwAuPoBWcWD": {
      "uid": "P4Lb4Fd8Mfac1gFFBdSgzIGp9t03",
      "imgUrl": [],
      "eventDate": "2025-04-11",
      "title": "MUSIC CLUB, ATULYAM 2025",
      "brochureUrl": "",
      "createdInSeconds": 1746249012619,
      "approved": true,
      "categoryId": "14",
      "created": "3 May 2025 at 10:40 AM",
      "author": "Kimjolly Lhouvum",
      "imgCaption": "With judges, Coordinators, participants and winner of Voice of Atulyam Damsing Konia (third from left).",
      "id": "6o2v6oRuDOwAuPoBWcWD",
      "content": "Damsing Konia CE22B032, NIT ARUNACHAL PRADESH won the WINNER in the VOICE OF ATULYAM on the theme of \"VOICE OF ATULYAM\" organized by MUSIC CLUB NIT ARUNACHAL PRADESH in association with ATULYAM 2025 NIT ARUNACHAL PRADESH, 2025-04-11"
    },
    "z7KpekfOIDx872AcJg2D": {
      "imgUrl": [],
      "brochureUrl": "",
      "title": "VOICE OF ATULYAM 2025",
      "categoryId": "14",
      "imgCaption": "",
      "author": "Kimjolly Lhouvum",
      "eventDate": "2025-04-11",
      "createdInSeconds": 1746249292967,
      "created": "3 May 2025 at 10:44 AM",
      "approved": true,
      "uid": "P4Lb4Fd8Mfac1gFFBdSgzIGp9t03",
      "id": "z7KpekfOIDx872AcJg2D",
      "content": "Rajdeep Chakraborty  ME21B016 MECHANICAL, NIT ARUNACHAL PRADESH won the First runner up in the VOICE OF ATULYAM on the theme of \"VOICE OF ATULYAM\" organized by MUSIC CLUB in association with ATULYAM 2025 NIT ARUNACHAL PRADESH, 2025-04-11"
    },
    "3oDE0a118HDks0pK3jNx": {
      "eventDate": "2025-04-11",
      "imgCaption": "Winner of Voice of Atulyam 2025 Damsing Konia (third from left) with judges, coordinators, and participants.",
      "title": "VOICE OF ATULYAM 2025",
      "createdInSeconds": 1746249565110,
      "created": "3 May 2025 at 10:49 AM",
      "imgUrl": [],
      "author": "Kimjolly Lhouvum",
      "approved": true,
      "brochureUrl": "",
      "uid": "P4Lb4Fd8Mfac1gFFBdSgzIGp9t03",
      "categoryId": "14",
      "id": "3oDE0a118HDks0pK3jNx",
      "content": "Damsing Konia CE22B032 CIVIL ENGINEERING, NIT ARUNACHAL PRADESH won the WINNER in the VOICE OF ATULYAM 2025 on the theme of \"VOICE OF ATULYAM 2025\" organized by MUSIC CLUB in association with ATULYAM 2025 NIT ARUNACHAL PRADESH, 2025-04-11"
    },
    "fuUASgPTwEJEZR4rKE2P": {
      "uid": "P4Lb4Fd8Mfac1gFFBdSgzIGp9t03",
      "eventDate": "2025-04-11",
      "author": "Kimjolly Lhouvum",
      "categoryId": "14",
      "approved": true,
      "title": "VOICE OF ATULYAM 2025",
      "createdInSeconds": 1746249840923,
      "brochureUrl": "",
      "imgUrl": [],
      "imgCaption": "",
      "created": "3 May 2025 at 10:54 AM",
      "id": "fuUASgPTwEJEZR4rKE2P",
      "content": "Khyoda Rimam  EE21B038 Electrical Engineering, NIT ARUNACHAL PRADESH won the Second runner up in the VOICE OF ATULYAM 2025 on the theme of \"VOICE OF ATULYAM 2025\" organized by MUSIC CLUB in association with ATULYAM 2025 NIT ARUNACHAL PRADESH, 2025-04-11"
    },
    "ogcoQMsp38hydeiUVdpY": {
      "imgCaption": "Winners, participants, judges and coordinators of BATTLE OF BANDS ",
      "categoryId": "14",
      "createdInSeconds": 1746250417654,
      "imgUrl": [],
      "created": "3 May 2025 at 11:03 AM",
      "brochureUrl": "",
      "uid": "P4Lb4Fd8Mfac1gFFBdSgzIGp9t03",
      "approved": true,
      "author": "Kimjolly Lhouvum",
      "title": "BATTLE OF BANDS",
      "eventDate": "2025-04-10",
      "id": "ogcoQMsp38hydeiUVdpY",
      "content": "Ashoung Singhi and band, Arunodaya University, Lekhi won the WINNER in the BATTLE OF BANDS on the theme of \"BATTLE OF BANDS\" organized by MUSIC CLUB in association with ATULYAM 2025 NIT ARUNACHAL PRADESH, 2025-04-10"
    },
    "OCqsmeTb9QjfBu5bBN2f": {
      "createdInSeconds": 1746250579020,
      "title": "BATTLE OF BANDS",
      "eventDate": "2025-04-10",
      "categoryId": "14",
      "created": "3 May 2025 at 11:06 AM",
      "author": "Kimjolly Lhouvum",
      "approved": true,
      "uid": "P4Lb4Fd8Mfac1gFFBdSgzIGp9t03",
      "imgCaption": "",
      "imgUrl": [],
      "brochureUrl": "",
      "id": "OCqsmeTb9QjfBu5bBN2f",
      "content": "HILL SIDE TRIBALS BAND, NIT ARUNACHAL PRADESH won the First runner up in the BATTLE OF BANDS on the theme of \"BATTLE OF BANDS\" organized by MUSIC CLUB in association with ATULYAM 2025 NIT ARUNACHAL PRADESH, 2025-04-10"
    },
    "KiLungNO3KWEPwo0eOlN": {
      "eventDate": "2025-03-24",
      "brochureUrl": "",
      "createdInSeconds": 1746450035560,
      "uid": "1meMTeaYftWPu0KVhmKhjj8h9Fu1",
      "created": "5 May 2025, 6:30 pm",
      "imgCaption": "",
      "categoryId": "15",
      "imgUrl": [],
      "title": "",
      "author": "Vijayakumar Kathirvel",
      "approved": true,
      "id": "KiLungNO3KWEPwo0eOlN",
      "content": "Two Day Workshop  on \"Academic Writing and Publications: Strategies for Excellence\" was organized by Dr. K. Vijayakumar, Assistant Professor, Dept of M&H and Dr. Nabakumar Pramanik Associate Professor Dean P&D NITAP,  The workshop was conducted by Dr. Sathyaraj Venkatesan, a distinguished Professor of English at the Department of Humanities and Social Sciences, NIT Tiruchirappalli. , at NIT AP, from 2025-03-24 to 2025-03-25."
    },
    "3ZegLm5nSYPWgSzmrDCL": {
      "uid": "1meMTeaYftWPu0KVhmKhjj8h9Fu1",
      "createdInSeconds": 1746451110213,
      "imgUrl": [],
      "created": "5 May 2025, 6:48 pm",
      "categoryId": "14",
      "author": "Vijayakumar Kathirvel",
      "approved": true,
      "eventDate": "2025-03-16",
      "brochureUrl": "",
      "title": "",
      "imgCaption": "Hiba Mangkum",
      "id": "3ZegLm5nSYPWgSzmrDCL",
      "content": "Mr. Hiba Mangkum, B.Tech Student from NIT Arunachal Pradesh won the top spot in the junior category in the Spelling Wizards \"a premier spelling competition for young minds aged 15-29 years\" organized by Department of Youth Affairs,  in association with Government of Arunachal Pradesh, 2025-03-16"
    },
    "Uan444PjT9Ggh6VG2sDf": {
      "uid": "1meMTeaYftWPu0KVhmKhjj8h9Fu1",
      "imgUrl": [],
      "createdInSeconds": 1746451304577,
      "approved": true,
      "title": "",
      "brochureUrl": "",
      "eventDate": "2025-05-01",
      "created": "5 May 2025, 6:51 pm",
      "categoryId": "14",
      "author": "Vijayakumar Kathirvel",
      "imgCaption": "",
      "id": "Uan444PjT9Ggh6VG2sDf",
      "content": "Ms. Deter Boje, B.Tech Student from NIT Arunachal Pradesh won the top spot in the senior category in the Spelling Wizards \"a premier spelling competition for young minds aged 15-29 years\" organized by Department of Youth Affairs,  in association with Government of Arunachal Pradesh, 2025-03-16"
    },
    "CREqTN91Rzmwap0Ro7ni": {
      "categoryId": "12",
      "brochureUrl": "",
      "imgCaption": "",
      "createdInSeconds": 1750767560838,
      "created": "24 Jun 2025, 5:49 pm",
      "approved": true,
      "author": "Nabakumar Pramanik",
      "eventDate": "2025-05-07",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "title": "",
      "imgUrl": [],
      "id": "CREqTN91Rzmwap0Ro7ni",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, BAS served as a *Reviewer* of \"Chemistry Select\". Wiley. 2025-05-07."
    },
    "w1SHbJn4UR3yeO8KBjwH": {
      "categoryId": "12",
      "eventDate": "2025-05-22",
      "author": "Nabakumar Pramanik",
      "createdInSeconds": 1750768029574,
      "created": "24 Jun 2025, 5:57 pm",
      "title": "",
      "imgUrl": [],
      "imgCaption": "",
      "brochureUrl": "",
      "approved": true,
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "id": "w1SHbJn4UR3yeO8KBjwH",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, BAS served as a *Reviewer* of \"Next Nanotechnology\". Elsevier. 2025-05-22."
    },
    "xEgHUg3ZRibY7NBaCeUR": {
      "createdInSeconds": 1750768905590,
      "imgUrl": [],
      "categoryId": "16",
      "eventDate": "2025-05-05",
      "imgCaption": "",
      "approved": true,
      "brochureUrl": "",
      "author": "Nabakumar Pramanik",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "created": "24 Jun 2025, 6:11 pm",
      "title": "",
      "id": "xEgHUg3ZRibY7NBaCeUR",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, BAS, attended a Programme on Establishing a Centre of Excellence  was organised  by Arunachal Pradesh State Council for Science and Technology (APSCST), Arunachal Pradesh   on the Emerging Technologies (CoE-STIR), from 2025-05-05 to 2025-05-05."
    },
    "U6rK5uZ0VtMaFkj3G7Yu": {
      "imgCaption": "",
      "uid": "6WoHMD9AyvPXoh8vZsskHHtV5hj2",
      "eventDate": "",
      "author": "Utpal Kumar Saha",
      "created": "25 Jun 2025, 5:24 pm",
      "imgUrl": [],
      "approved": true,
      "brochureUrl": "",
      "title": "",
      "categoryId": "7",
      "createdInSeconds": 1750852447141,
      "id": "U6rK5uZ0VtMaFkj3G7Yu",
      "content": "Biswas Arpita, Ram Prakash Sharma, Utpal Kumar Saha (2025). Sensitivity analysis of heat transfer in water- and kerosene-based trihybrid nanofluids in MHD Casson flow. *Multiscale and Multidisciplinary Modeling, Experiments and Design, Volume No.8 (Article no. 354), pp. 1-28 . https://doi.org/10.1007/s41939-025-00934-9"
    },
    "Y8ARm0JBVZ64qcYuM7Sd": {
      "categoryId": "1",
      "createdInSeconds": 1751214203316,
      "brochureUrl": "",
      "approved": true,
      "author": "A Vanav Kumar",
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "eventDate": "2025-05-31",
      "title": "",
      "imgUrl": [],
      "imgCaption": "MEMORANDUM OF UNDERSTANDING, C-DAC, Pune, 31, May 2025",
      "created": "29 Jun 2025, 9:53 pm",
      "id": "Y8ARm0JBVZ64qcYuM7Sd",
      "content": "National Institute of Technology, Arunachal Pradesh-791113, India and Center for Development of Advanced Computing, Pune, C-DAC’s Innovation Park, Panchavati, off Pashan Road, Pune-411008, Maharashtra, India  signed a Memorandum of Understanding under High Performance Computing, National Super Computer Mission (NSM), National Initiative of the Government of India. Installing the Super Computer PARAM VIDYA, Education and Research in HPC, National Institute of Technology, Arunachal Pradesh. During the event, Prof. (Dr) Mohan V Aware, Director, National Institute of Technology, Arunachal Pradesh-791113, India , with Mr. Sanjay A Wandhekar, Director, C-DAC, C-DAC’s Innovation Park,Panchavati, off Pashan Road, Pune-411008, Maharashtra, India were present. Mr Ashish Kuvelkar, Scientist-G & Nodal Coordinator, C-DAC’s Innovation Park, Panchavati, off Pashan Road, Pune-411008, Maharashtra, India  and Dr. A. Vanav Kumar, Associate Professor and Nodal Coordinator (NSM), National Institute of Technology, Arunachal Pradesh - 791113, India had witnessed the event. 2025-05-31"
    },
    "nYaCeKa0yoLfU3YUY09a": {
      "eventDate": "",
      "createdInSeconds": 1751264922870,
      "approved": true,
      "title": "",
      "imgUrl": [],
      "created": "30 Jun 2025, 11:58 am",
      "brochureUrl": "",
      "author": "Pratap Kumar Swain",
      "uid": "PmjHqwBk7FSjkE9RIXgMZp2ncjk2",
      "categoryId": "7",
      "imgCaption": "",
      "id": "nYaCeKa0yoLfU3YUY09a",
      "content": "Ngomle, M.Gogoi, D.Swain, P. K.. (2024). Study of Structural and Optoelectronic Properties of Cubic CsXBr3 (X = Ge, Sn and Pb) Perovskite for Photovoltaic Devices Efficiency with 19.50%.. *Journal of Inorganic and Organometallic Polymers and Materials* *35*(7), 03882. https://doi.org/10.1007/s10904-025-03882-6"
    },
    "fsZQU2Tkl0QQ4LRPA6Mz": {
      "brochureUrl": "",
      "created": "30 Jun 2025, 12:05 pm",
      "imgUrl": [],
      "categoryId": "7",
      "eventDate": "",
      "author": "Pratap Kumar Swain",
      "uid": "PmjHqwBk7FSjkE9RIXgMZp2ncjk2",
      "createdInSeconds": 1751265315329,
      "title": "",
      "imgCaption": "",
      "approved": true,
      "id": "fsZQU2Tkl0QQ4LRPA6Mz",
      "content": "Tasso, Y,.Swain, P. K.,.Mohanta,  S. K., . (2025). First principles investigation of structural, electrical, mechanical, optical and thermoelectric properties of half-Heusler semiconductor KBaAs. *Materials Science and Engineering: B* *321*,  118438. https://doi.org/10.1016/j.mseb.2025.118438"
    },
    "RmBzNnhsWCWW7Z77RtX6": {
      "categoryId": "9",
      "author": "Pratap Kumar Swain",
      "approved": true,
      "imgCaption": "",
      "brochureUrl": "",
      "title": "",
      "createdInSeconds": 1751349314309,
      "uid": "PmjHqwBk7FSjkE9RIXgMZp2ncjk2",
      "eventDate": "2025-06-05",
      "imgUrl": [],
      "created": "1 Jul 2025, 11:25 am",
      "id": "RmBzNnhsWCWW7Z77RtX6",
      "content": "SWAIN, P K. *MAGNETICALLY SEPARABLE ACTIVATED CARBON FOR REMOVAL  OF HEAVY METAL FROM GROUND WATER* [Paper presentation]. Third International British Congress on Interdisciplinary Scientific Research & Practice, London, United Kingdom , from 2025-06-05 to 2025-06-08. "
    },
    "BoiAu0mlstrDFlmqtdA2": {
      "author": "Rajen Pudur",
      "title": "",
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "createdInSeconds": 1751353591742,
      "brochureUrl": "",
      "categoryId": "7",
      "imgCaption": "",
      "approved": true,
      "created": "1 Jul 2025, 12:36 pm",
      "eventDate": "",
      "imgUrl": [],
      "id": "BoiAu0mlstrDFlmqtdA2",
      "content": "Rajak, M.K. and Pudur, R.  (2025). Adaptive hybrid PSO-GD optimized phase-locked loop for robust grid synchronization in renewable energy systems. *COMPEL - The international journal for computation and mathematics in electrical and electronic engineering*. https://doi.org/10.1108/COMPEL-11-2024-0463 "
    },
    "HnNGcVRRzU3kqUplIqML": {
      "eventDate": "",
      "createdInSeconds": 1751353680699,
      "approved": true,
      "title": "",
      "imgUrl": [],
      "brochureUrl": "",
      "created": "1 Jul 2025, 12:38 pm",
      "author": "Rajen Pudur",
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "categoryId": "7",
      "imgCaption": "",
      "id": "HnNGcVRRzU3kqUplIqML",
      "content": "Rajak, M.K. and Pudur, R.  (2025). Steady-state analysis of parallel-connected self-excited induction generators with hybrid excitation using fixed-point iteration method. *COMPEL - The international journal for computation and mathematics in electrical and electronic engineering*. https://doi.org/10.1108/COMPEL-10-2024-0444"
    },
    "2cHZuff6IG5NinpPGIhu": {
      "imgUrl": [],
      "created": "1 Jul 2025, 12:39 pm",
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "imgCaption": "",
      "author": "Rajen Pudur",
      "createdInSeconds": 1751353753268,
      "eventDate": "",
      "title": "",
      "approved": true,
      "categoryId": "7",
      "brochureUrl": "",
      "id": "2cHZuff6IG5NinpPGIhu",
      "content": "Rajak, M.K., Pudur, R(2025). Multiobjective adaptive predictive virtual synchronous generator control strategy for grid stability and renewable integration. *Scientific Reports *. https://doi.org/10.1038/s41598-025-93721-y "
    },
    "Ii4pBcRdx5MbGFnWHkVS": {
      "created": "1 Jul 2025, 12:40 pm",
      "categoryId": "7",
      "brochureUrl": "",
      "imgUrl": [],
      "author": "Rajen Pudur",
      "imgCaption": "",
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "eventDate": "",
      "approved": true,
      "createdInSeconds": 1751353852020,
      "title": "",
      "id": "Ii4pBcRdx5MbGFnWHkVS",
      "content": "Mrinal KantiRajak, Rajen Pudur (2025). Deep reinforcement learning framework for adaptive power control in grid-forming inverters: A multi-objective optimization approach.. *Journal of Renewable and Sustainable Energy * *17*. https://doi.org/10.1063/5.0249385 "
    },
    "ht1IPMCjYNaIwZyCPHvB": {
      "imgCaption": "",
      "author": "Rajen Pudur",
      "approved": true,
      "categoryId": "7",
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "created": "1 Jul 2025, 12:42 pm",
      "title": "",
      "eventDate": "",
      "brochureUrl": "",
      "createdInSeconds": 1751353928027,
      "imgUrl": [],
      "id": "ht1IPMCjYNaIwZyCPHvB",
      "content": "Samanta, Jotirmoy, RalliSangno, and Rajen Pudur.  (2025). A Modified Control Scheme to Mitigate Harmonics, Improve Voltage Regulation & Power Factor using Single-Phase Shunt Active Power Filter.. *.\" Suranaree Journal of Science & Technology *. "
    },
    "xvMpWY0OHsLORnL2UwtK": {
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "imgUrl": [],
      "createdInSeconds": 1751354254563,
      "title": "",
      "approved": true,
      "brochureUrl": "",
      "created": "1 Jul 2025, 12:47 pm",
      "eventDate": "",
      "author": "Rajen Pudur",
      "categoryId": "7",
      "imgCaption": "",
      "id": "xvMpWY0OHsLORnL2UwtK",
      "content": "Samanta, J., Chakraborty, S., Sangno, R. and Pudur, R., (2025). Study of power quality issues in a renewable-driven self-excited induction generator due to different loads at edge-off grid system.. *e-Prime-Advances in Electrical Engineering, Electronics and Energy* *11*. https://doi.org/10.1016/j.prime.2024.100885 "
    },
    "k261H9AhjILUU0G51mQQ": {
      "author": "Rajen Pudur",
      "imgCaption": "",
      "brochureUrl": "",
      "imgUrl": [],
      "createdInSeconds": 1751354811355,
      "created": "1 Jul 2025, 12:56 pm",
      "title": "",
      "approved": true,
      "eventDate": "2025-06-18",
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "categoryId": "13",
      "id": "k261H9AhjILUU0G51mQQ",
      "content": "Dr Rajen Pudur, Associate Professor, Electrical Engineeing was *The Chair of Panel Session* at IEEE Guwahati Subsection, organised by NERIST, from 2025-06-18 to 2025-06-19."
    },
    "doWW0zGvS72f5eX0LebO": {
      "categoryId": "12",
      "brochureUrl": "",
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "created": "1 Jul 2025, 12:59 pm",
      "author": "Rajen Pudur",
      "title": "",
      "imgUrl": [],
      "createdInSeconds": 1751354966946,
      "eventDate": "2025-05-16",
      "imgCaption": "",
      "approved": true,
      "id": "doWW0zGvS72f5eX0LebO",
      "content": "Dr Rajen Pudur, Associate Professor, Electrical Engineering served as a *Reviewer* of \"Results In Engineering\". Elsevier . 2025-05-16."
    },
    "sFn5fHs8SmeoL5btXZ0V": {
      "author": "Rajen Pudur",
      "createdInSeconds": 1751355080891,
      "title": "",
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "approved": true,
      "categoryId": "12",
      "created": "1 Jul 2025, 1:01 pm",
      "brochureUrl": "",
      "eventDate": "2025-06-18",
      "imgCaption": "",
      "imgUrl": [],
      "id": "sFn5fHs8SmeoL5btXZ0V",
      "content": "Dr Rajen Pudur, Associate Professor, Electrical Engineering served as a *Reviewer* of \"IEEE SEFET 2025\". IEEE. 2025-06-18."
    },
    "rpZd3SUipz3ToVHZGS1g": {
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "title": "",
      "approved": true,
      "categoryId": "12",
      "author": "Rajen Pudur",
      "created": "1 Jul 2025, 1:03 pm",
      "brochureUrl": "",
      "imgUrl": [],
      "imgCaption": "",
      "createdInSeconds": 1751355185756,
      "eventDate": "2025-06-20",
      "id": "rpZd3SUipz3ToVHZGS1g",
      "content": "Dr Rajen Pudur, Associate Professor, Electrical Engineering served as a *Reviewer* of \"IEEE NE NICCE 2025\". IEEE. 2025-06-20."
    },
    "gvET66KrcpBmwQdWkKDF": {
      "title": "",
      "created": "1 Jul 2025, 1:04 pm",
      "brochureUrl": "",
      "uid": "GFyxQWofARVG1Ez4zKbWXAjXHbr2",
      "createdInSeconds": 1751355240115,
      "approved": true,
      "imgCaption": "",
      "imgUrl": [],
      "eventDate": "2025-06-04",
      "author": "Rajen Pudur",
      "categoryId": "12",
      "id": "gvET66KrcpBmwQdWkKDF",
      "content": "Dr Rajen Pudur, Associate Professor, Electrical Engineering served as a *Reviewer* of \"IEEE GCON 2025\". IEEE. 2025-06-04."
    },
    "hp8RVGK1d1wM4UQI51rx": {
      "categoryId": "3",
      "author": "Sahadev Roy",
      "imgUrl": [],
      "brochureUrl": "",
      "createdInSeconds": 1755753540823,
      "eventDate": "2025-07-25",
      "imgCaption": "Technological Innovation Hub and Startup Ecosystem Development by Prof. (Dr.) Santosha Kumar Dwivedy ",
      "approved": true,
      "created": "21 Aug 2025, 10:49 am",
      "uid": "zyYjfIjQ01XNIjOVxu9UPh0HfKC2",
      "title": "",
      "id": "hp8RVGK1d1wM4UQI51rx",
      "content": "Prof. (Dr.) Santosha Kumar Dwivedy, Professor (Hug), Department of ME, Indian Institute of Technology Guwahati visited and delivered a Special Lecture on \"Technological Innovation Hub and Startup Ecosystem Development\" organised by Dr. Sahadev Roy, 2025-07-25"
    },
    "GLUyZVgQJZ8UqGTEPipl": {
      "imgUrl": [],
      "categoryId": "7",
      "title": "",
      "approved": true,
      "brochureUrl": "",
      "imgCaption": "",
      "created": "21-Aug-2025, 12:34 pm",
      "eventDate": "",
      "uid": "L3JwBJAHf5aQIyAwvljtNSKYV9z1",
      "author": "M Berlin",
      "createdInSeconds": 1755759896452,
      "id": "GLUyZVgQJZ8UqGTEPipl",
      "content": "Lawrence, JINO .Berlin , MOHANADHAS.Natarajan , NARAYANAN.Vasudevan , MANGOTTRI . (2025). Confronting the Implications of Subsurface Heterogeneity on the Mass Transfer and Transport of Nitrate through Layered Porous Media. *Journal of Porous Media*. https://doi.org/10.1615/JPorMedia.2025053663"
    },
    "o5C8ZUZxAWvGhZcm2BTy": {
      "title": "",
      "uid": "L3JwBJAHf5aQIyAwvljtNSKYV9z1",
      "author": "M Berlin",
      "approved": true,
      "created": "21-Aug-2025, 12:37 pm",
      "createdInSeconds": 1755760030885,
      "eventDate": "",
      "categoryId": "7",
      "imgUrl": [],
      "brochureUrl": "",
      "imgCaption": "",
      "id": "o5C8ZUZxAWvGhZcm2BTy",
      "content": "Ahmed, NADIM .Berlin , MOHANADHAS . (2025). Influence of river vegetation on sediment transport and erosion mitigation: A review. *Research in Cold and Arid Regions*. https://doi.org/10.1016/j.rcar.2025.07.001"
    },
    "REzD7ncwKwQRUcfCpXnP": {
      "author": "M Berlin",
      "title": "",
      "brochureUrl": "",
      "approved": true,
      "imgCaption": "",
      "created": "21-Aug-2025, 12:39 pm",
      "uid": "L3JwBJAHf5aQIyAwvljtNSKYV9z1",
      "categoryId": "7",
      "eventDate": "",
      "createdInSeconds": 1755760140926,
      "imgUrl": [],
      "id": "REzD7ncwKwQRUcfCpXnP",
      "content": "Radha , PALPI BORUAH.Berlin , MOHANADHAS.Jayakesh , K. (2025). Microbially Induced Calcite Precipitation for Soil Stabilization: A State-of-Art Review. *Geomicrobiology Journal*. https://doi.org/10.1080/01490451.2025.2545389"
    },
    "xjJygvcamjtjRXKMbIE2": {
      "created": "21 Aug 2025, 12:48 pm",
      "categoryId": "7",
      "brochureUrl": "",
      "author": "Nabakumar Pramanik",
      "imgUrl": [],
      "imgCaption": "",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "approved": true,
      "eventDate": "",
      "createdInSeconds": 1755760714981,
      "title": "",
      "id": "xjJygvcamjtjRXKMbIE2",
      "content": "Ghosh, S..Malakar, C. C. .Giri, S. .Pramanik, N. .Atta, A. K. . (2025). Triazole-Linked Pyrene Sugar Analogue for Recognition of Picric Acid in Aqueous Medium. *Chemistry Select * *10*(25), e00854 (1-9). https://doi.org/10.1002/slct.202500854"
    },
    "BrY8Ye12o34Q9M0MZXqx": {
      "eventDate": "2025-07-14",
      "title": "",
      "categoryId": "12",
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "approved": true,
      "imgUrl": [],
      "author": "Nabakumar Pramanik",
      "created": "21 Aug 2025, 12:54 pm",
      "brochureUrl": "",
      "createdInSeconds": 1755761069005,
      "imgCaption": "",
      "id": "BrY8Ye12o34Q9M0MZXqx",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, Basic and Applied Science served as a *Reviewer* of \"International Journal of Biological Macromolecules\". Elsevier. 2025-07-14."
    },
    "NNUhY2EnPOtoPw0yQfyt": {
      "brochureUrl": "",
      "approved": true,
      "uid": "t0INQ2R07kW0GLHik5IwSKaveqe2",
      "created": "21 Aug 2025, 1:01 pm",
      "author": "Nabakumar Pramanik",
      "imgUrl": [],
      "eventDate": "2025-07-24",
      "createdInSeconds": 1755761486580,
      "title": "",
      "imgCaption": "",
      "categoryId": "12",
      "id": "NNUhY2EnPOtoPw0yQfyt",
      "content": "Dr. Nabakumar Pramanik, Associate Professor, Basic and Applied Science served as a *Reviewer* of \"Results in Chemistry\". Elsevier. 2025-07-24."
    },
    "nZRRViBM2XshsLRnIOqu": {
      "brochureUrl": "",
      "approved": true,
      "created": "1 Sept 2025, 11:24 pm",
      "author": "A Vanav Kumar",
      "title": "",
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "imgUrl": [],
      "createdInSeconds": 1756749295210,
      "eventDate": "2025-06-23",
      "imgCaption": "",
      "categoryId": "11",
      "id": "nZRRViBM2XshsLRnIOqu",
      "content": "A. Vanav Kumar, Associate Professor, Mathematics Division, Department of Basic and Applied Science attended FDP on \"“Demystifying Quantum Computing: Principles, Applications, and Future Directions”\", organised by Department of Electronics and Communication Engineering (ECE), Anurag University, from 2025-06-23 to 2025-06-27."
    },
    "uSX9PNjIslgijdKts2Lf": {
      "brochureUrl": "",
      "title": "",
      "approved": true,
      "author": "A Vanav Kumar",
      "imgCaption": "",
      "eventDate": "2025-06-25",
      "categoryId": "11",
      "uid": "g9iABHJTSbWhH4XJ2ezBYtXQNus2",
      "imgUrl": [],
      "created": "1 Sept 2025, 11:29 pm",
      "createdInSeconds": 1756749580495,
      "id": "uSX9PNjIslgijdKts2Lf",
      "content": "A Vanav Kumar, Associate Professor, Mathematics Division, Department of Basic and Applied Science attended Workshop on \"Introductory Training on Domain Specific HPC Software Packages\", organised by CDAC, Pune and IIT, Goa, from 2025-06-25 to 2025-07-25."
    },
    "Dz5tUqhnMJfGUp7Xi03Z": {
      "eventDate": "2025-07-08",
      "createdInSeconds": 1756771521927,
      "author": "Ram Prakash Sharma",
      "categoryId": "12",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "imgUrl": [],
      "imgCaption": "",
      "title": "",
      "approved": true,
      "brochureUrl": "",
      "created": "2 Sept 2025, 5:35 am",
      "id": "Dz5tUqhnMJfGUp7Xi03Z",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \"Alexandria Engineering Journal\". Elsevier B.V. 2025-07-08."
    },
    "FGGTSNsa7Af7wUF4rseg": {
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "created": "2 Sept 2025, 5:36 am",
      "approved": true,
      "eventDate": "2025-09-17",
      "imgUrl": [],
      "title": "",
      "imgCaption": "",
      "author": "Ram Prakash Sharma",
      "categoryId": "12",
      "brochureUrl": "",
      "createdInSeconds": 1756771598817,
      "id": "FGGTSNsa7Af7wUF4rseg",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \"Case Studies in Thermal Engineering \". Elsevier B.V. 2025-07-10."
    },
    "bNowasf5NIi7vBPvqBmJ": {
      "title": "",
      "eventDate": "2025-09-27",
      "approved": true,
      "created": "2 Sept 2025, 5:37 am",
      "imgCaption": "",
      "brochureUrl": "",
      "createdInSeconds": 1756771671848,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "categoryId": "12",
      "author": "Ram Prakash Sharma",
      "imgUrl": [],
      "id": "bNowasf5NIi7vBPvqBmJ",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \"Engineering Application for Artificial Intelligent \". Elsevier Ltd. 2025-07-18."
    },
    "JNpI9mBGsg65KVhfu2PL": {
      "imgCaption": "",
      "imgUrl": [],
      "created": "2 Sept 2025, 5:38 am",
      "title": "",
      "eventDate": "2025-09-22",
      "createdInSeconds": 1756771725339,
      "brochureUrl": "",
      "categoryId": "12",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "author": "Ram Prakash Sharma",
      "approved": true,
      "id": "JNpI9mBGsg65KVhfu2PL",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \"Indian Journal of Chemical Technology \". CSIR-NIScPR . 2025-07-18."
    },
    "A8lHJhoaOpe3JOKG6nSE": {
      "createdInSeconds": 1756771769602,
      "eventDate": "2025-09-24",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "imgUrl": [],
      "title": "",
      "author": "Ram Prakash Sharma",
      "created": "2 Sept 2025, 5:39 am",
      "imgCaption": "",
      "categoryId": "12",
      "approved": true,
      "brochureUrl": "",
      "id": "A8lHJhoaOpe3JOKG6nSE",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \"International Journal for Numerical Methods \". 2025-07-18."
    },
    "BobZCSgH2CEqN3HNnkBm": {
      "eventDate": "2025-09-14",
      "createdInSeconds": 1756771821056,
      "approved": true,
      "imgUrl": [],
      "title": "",
      "categoryId": "12",
      "brochureUrl": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "created": "2 Sept 2025, 5:40 am",
      "author": "Ram Prakash Sharma",
      "imgCaption": "",
      "id": "BobZCSgH2CEqN3HNnkBm",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \" International Journal of Advances in Engineering Sciences and Applied Mathematics\". Springer Nature. 2025-07-27."
    },
    "AtGgSUk2C8wjMuBNBF5e": {
      "author": "Ram Prakash Sharma",
      "createdInSeconds": 1756771868324,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "eventDate": "2025-09-06",
      "imgUrl": [],
      "categoryId": "12",
      "approved": true,
      "created": "2 Sept 2025, 5:41 am",
      "imgCaption": "",
      "brochureUrl": "",
      "title": "",
      "id": "AtGgSUk2C8wjMuBNBF5e",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \" Journal of Nanofluids\". American Scientific Publishers. 2025-07-27."
    },
    "7D7t32uvCuTbnWlv39Cu": {
      "approved": true,
      "brochureUrl": "",
      "imgUrl": [],
      "title": "",
      "imgCaption": "",
      "categoryId": "12",
      "author": "Ram Prakash Sharma",
      "eventDate": "2025-09-21",
      "created": "2 Sept 2025, 5:42 am",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "createdInSeconds": 1756771939948,
      "id": "7D7t32uvCuTbnWlv39Cu",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \" physical science international journal \" Academic Press. 2025-07-26."
    },
    "U4kbLiytOGxPs1KgbHyd": {
      "imgUrl": [],
      "imgCaption": "",
      "author": "Ram Prakash Sharma",
      "eventDate": "2025-09-16",
      "title": "",
      "createdInSeconds": 1756772014618,
      "created": "2 Sept 2025, 5:43 am",
      "brochureUrl": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "categoryId": "12",
      "approved": true,
      "id": "U4kbLiytOGxPs1KgbHyd",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \"Physics of Fluid\". AIP Publisher 2025-07-15."
    },
    "8uw5mXDWH1AqzMF1KQnM": {
      "author": "Ram Prakash Sharma",
      "title": "",
      "brochureUrl": "",
      "approved": true,
      "imgCaption": "",
      "created": "2 Sept 2025, 5:44 am",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "categoryId": "12",
      "createdInSeconds": 1756772074008,
      "eventDate": "2025-09-18",
      "imgUrl": [],
      "id": "8uw5mXDWH1AqzMF1KQnM",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \" Scientific Report\". Springer Nature. 2025-07-27"
    },
    "SSbYCL7fF20tufMoxCHJ": {
      "eventDate": "2025-09-15",
      "createdInSeconds": 1756772127892,
      "brochureUrl": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "imgCaption": "",
      "title": "",
      "approved": true,
      "imgUrl": [],
      "author": "Ram Prakash Sharma",
      "categoryId": "12",
      "created": "2 Sept 2025, 5:45 am",
      "id": "SSbYCL7fF20tufMoxCHJ",
      "content": "Prof. Ram Prakash Sharma, Professor, Professor, Department of Mechanical Engineering served as a Reviewer of \"Sigma Journal of Engineering and Natural Sciences\". Yildiz Technical University. 2025-07-15."
    },
    "DLJlPmC9yYCMCpeXcFkI": {
      "createdInSeconds": 1756772168204,
      "eventDate": "2025-09-23",
      "imgUrl": [],
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "title": "",
      "author": "Ram Prakash Sharma",
      "created": "2 Sept 2025, 5:46 am",
      "imgCaption": "",
      "categoryId": "12",
      "approved": true,
      "brochureUrl": "",
      "id": "DLJlPmC9yYCMCpeXcFkI",
      "content": "Prof. Ram Prakash Sharma, Professor, Professor, Department of Mechanical Engineering served as a Reviewer of \" Surfaces and Interfaces\". Elsevier Ltd. 2025-07-15"
    },
    "j1jeDEFzLDFnNAoFe0cT": {
      "categoryId": "12",
      "author": "Ram Prakash Sharma",
      "created": "2 Sept 2025, 5:47 am",
      "eventDate": "2025-09-12",
      "approved": true,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "brochureUrl": "",
      "imgUrl": [],
      "imgCaption": "",
      "createdInSeconds": 1756772228890,
      "title": "",
      "id": "j1jeDEFzLDFnNAoFe0cT",
      "content": "Prof. Ram Prakash Sharma, Professor, Professor, Department of Mechanical Engineering served as a Reviewer of \" ZAMM Zeitschrift fur Angewandte Mathematik und Mechanik\". Wiley-VCH Verlag. 2025-07-24."
    },
    "l8HBLJX09V0tGaTYhmmg": {
      "categoryId": "12",
      "title": "",
      "author": "Ram Prakash Sharma",
      "imgCaption": "",
      "created": "2 Sept 2025, 5:47 am",
      "eventDate": "2025-09-06",
      "approved": true,
      "brochureUrl": "",
      "imgUrl": [],
      "createdInSeconds": 1756772275072,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "id": "l8HBLJX09V0tGaTYhmmg",
      "content": "Prof. Ram Prakash Sharma, Professor, Professor, Department of Mechanical Engineering served as a Reviewer of \" ZAMM Zeitschrift fur Angewandte Mathematik und Mechanik\". Wiley-VCH Verlag. 2025-08-24."
    },
    "riSMQRqVfL03Wh2Gr0II": {
      "brochureUrl": "",
      "imgCaption": "",
      "created": "2 Sept 2025, 5:48 am",
      "author": "Ram Prakash Sharma",
      "title": "",
      "imgUrl": [],
      "eventDate": "2025-09-24",
      "approved": true,
      "createdInSeconds": 1756772329648,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "categoryId": "12",
      "id": "riSMQRqVfL03Wh2Gr0II",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \"Physics of Fluid\". AIP Publisher 2025-08-22."
    },
    "S4LNioAr93ojP5nLEhks": {
      "eventDate": "2025-09-14",
      "brochureUrl": "",
      "created": "2 Sept 2025, 5:49 am",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "author": "Ram Prakash Sharma",
      "createdInSeconds": 1756772369153,
      "imgCaption": "",
      "title": "",
      "imgUrl": [],
      "approved": true,
      "categoryId": "12",
      "id": "S4LNioAr93ojP5nLEhks",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering served as a Reviewer of \" Advanced Engineering Materials\".  Wiley-VCH Verlag, 2025-08-03."
    },
    "BFy9JhileGbXfQPLhSEU": {
      "title": "",
      "imgCaption": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "approved": true,
      "eventDate": "",
      "created": "2 Sept 2025, 5:57 am",
      "imgUrl": [],
      "createdInSeconds": 1756772876716,
      "categoryId": "7",
      "author": "Ram Prakash Sharma",
      "brochureUrl": "",
      "id": "BFy9JhileGbXfQPLhSEU",
      "content": "Rajat Srivastava, Ram Prakash Sharma, Response Surface Method-Based Optimization of Thermal Transfer Rate in Hybrid Nanofluid Flow Over a Porous Stretching Sheet with Multiple Slip Condition, Journal of Applied and Computational Mechanics,  (2025) 1-11 Publisher: Shahid Chamran University of Ahvaz H Index: 41 IF: 3.4\tDOI: 10.22055/jacm.2025.48570.5333"
    },
    "X49gQEmeN6EAgyGAwdoI": {
      "imgCaption": "",
      "brochureUrl": "",
      "title": "",
      "created": "2 Sept 2025, 6:01 am",
      "author": "Ram Prakash Sharma",
      "eventDate": "",
      "imgUrl": [],
      "categoryId": "7",
      "approved": true,
      "createdInSeconds": 1756773064307,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "id": "X49gQEmeN6EAgyGAwdoI",
      "content": "S. R. Mishra, Ram Prakash Sharma, Rupa Baithalu, Laxmipriya Swain, Analytical approach on free convection of time-dependent Casson fluid over a vertical expanding surface with Hall current, Physics of Fluids 37  (2025) 083123 https://doi.org/10.1063/5.0285580  IF-4.3, HI-211, Q1"
    },
    "suI6i9hG4Pgmxn6CkGpx": {
      "categoryId": "7",
      "title": "",
      "eventDate": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "brochureUrl": "",
      "author": "Ram Prakash Sharma",
      "imgUrl": [],
      "imgCaption": "",
      "created": "2 Sept 2025, 6:07 am",
      "approved": true,
      "createdInSeconds": 1756773446784,
      "id": "suI6i9hG4Pgmxn6CkGpx",
      "content": "Rajaram Mohanty, Pinakeswar Mahanta, Abinash Mahapatro, Ram Prakash Sharma, Assessment of a Heat Exchanger's Efficiency in a Fluidized Bed Gasifier for Biomass Gasification, International Journal of Energy for a Clean Environment (2025). DOI: 10.1615/InterJEnerCleanEnv.2025058341, SCOPUS, IF-  H Index: 21. Publisher: Begell House Inc."
    },
    "4FMGmDnF3mSyPpFMGRTR": {
      "imgCaption": "",
      "created": "2 Sept 2025, 6:09 am",
      "approved": true,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "categoryId": "7",
      "brochureUrl": "",
      "imgUrl": [],
      "author": "Ram Prakash Sharma",
      "createdInSeconds": 1756773562032,
      "title": "",
      "eventDate": "",
      "id": "4FMGmDnF3mSyPpFMGRTR",
      "content": "Ram Prakash Sharma, Chandralekha Mahanta, Debasish Gorai, Entropy optimization in magnetized uranium dioxide nanofluid flow through a porous cone-disk apparatus with trio dissipation using an artificial neural network, Physics of Fluids, Physics of Fluids 37, 073135 (2025) SCIE Q1 HI: 211, IF: 4.3, Q1, Publisher: AIP PUBLISHING, 1305 WALT WHITMAN RD, STE 300, MELVILLE, USA, NY, 11747-4501 https://doi.org/10.1063/5.0281484"
    },
    "Aj7baiJTWXqmzhzSpR7R": {
      "categoryId": "7",
      "imgUrl": [],
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "brochureUrl": "",
      "createdInSeconds": 1756773655324,
      "title": "",
      "author": "Ram Prakash Sharma",
      "imgCaption": "",
      "created": "2 Sept 2025, 6:10 am",
      "approved": true,
      "eventDate": "",
      "id": "Aj7baiJTWXqmzhzSpR7R",
      "content": "Abhishek Sharma, Ram Prakash Sharma, Arpita Biswas, Shaik Mohammed Ibrahim, Exploring the impact of nanoparticle aggregation in parabolic trough solar collectors with a neural network-based predictions for enhanced thermal performance, Solar Energy Materials and Solar Cells 293 (2025) 113866. H Index: 227, IF: 6.3, Q1, Publisher: Elsevier  https://doi.org/10.1016/j.solmat.2025.113866"
    },
    "xjuaEyN49VYXPSanCNa2": {
      "createdInSeconds": 1756773772593,
      "author": "Ram Prakash Sharma",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "brochureUrl": "",
      "approved": true,
      "created": "2 Sept 2025, 6:12 am",
      "eventDate": "",
      "imgUrl": [],
      "title": "",
      "categoryId": "7",
      "imgCaption": "",
      "id": "xjuaEyN49VYXPSanCNa2",
      "content": "Rajaram Mohanty, Pinakeswar Mahanta, Abinash Mahapatro, Ram Prakash Sharma, Hydrogen Rich Syngas Production from Catalytic Gasification of Pinewood in A Fluidized Bed Gasifier Using Taguchi Optimization Technique, International Journal of Energy for a Clean Environment (2025).  SCOPUS, H Index: 21. Publisher: Begell house Inc. https://doi.org/10.1615/InterJEnerCleanEnv.2025058337"
    },
    "ttYkfIRXoVfsOC6Bo87U": {
      "created": "2 Sept 2025, 6:16 am",
      "approved": true,
      "imgUrl": [],
      "author": "Ram Prakash Sharma",
      "imgCaption": "",
      "eventDate": "",
      "brochureUrl": "",
      "title": "",
      "categoryId": "7",
      "createdInSeconds": 1756773997369,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "id": "ttYkfIRXoVfsOC6Bo87U",
      "content": "Rajaram Mohanty, Pinakeswar Mahanta, Ram Prakash Sharma,  Recent Advances in Biomass Gasification to Improve the Quality of Syngas: A Comprehensive Review, Published by the American Chemical Society (ACS), Industrial & Engineering Chemistry Research, 2025, 64, 28, 13950–13965, H Index: 267, IF: 3.9 Publisher: American Chemical Society. Q1  https://doi.org/10.1021/acs.iecr.5c01388  "
    },
    "wAbUuKu19grnTvb4PHW7": {
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "eventDate": "",
      "approved": true,
      "imgCaption": "",
      "imgUrl": [],
      "author": "Ram Prakash Sharma",
      "created": "2 Sept 2025, 6:20 am",
      "categoryId": "7",
      "title": "",
      "createdInSeconds": 1756774219906,
      "brochureUrl": "",
      "id": "wAbUuKu19grnTvb4PHW7",
      "content": "Chandralekha Mahanta, Ram Prakash Sharma,  Neural network-driven analysis of different non-Newtonian fluids over a deformable melting surface with nonlinear radiation and slip effects, Multiscale and Multidisciplinary Modeling, Experiments and Design 8 (2025) Article number 372, H index: 19, IF: 2.0, PUBLISHER:  SPRINGERNATURE, Q2, DOI: https://doi.org/10.1007/s41939-025-00953-6 "
    },
    "6Qp38c78JlIDrnm0wkmI": {
      "imgUrl": [],
      "brochureUrl": "",
      "imgCaption": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "approved": true,
      "createdInSeconds": 1756774294624,
      "created": "2 Sept 2025, 6:21 am",
      "categoryId": "7",
      "author": "Ram Prakash Sharma",
      "title": "",
      "eventDate": "",
      "id": "6Qp38c78JlIDrnm0wkmI",
      "content": "Abhishek Sharma, and Ram Prakash Sharma, Utilizing neural networks to illustrate the dynamics of viscous fluid flow over curved surface with homogeneous and heterogeneous reactions, Engineering Applications of Artificial Intelligence, 159 (2025) 111629  H index: 149, IF: 8.0 , Q1, Publisher:  Elsevier Ltd, DOI: https://doi.org/10.1016/j.engappai.2025.111629\t\t\t\t\t"
    },
    "n0HTKhJqE59YliD19ZMe": {
      "eventDate": "2025-09-30",
      "brochureUrl": "",
      "approved": true,
      "author": "Ram Prakash Sharma",
      "categoryId": "15",
      "imgCaption": "NIT Arunachal Pradesh Team in the valedictory ceremony  ",
      "createdInSeconds": 1756775081325,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "title": "",
      "imgUrl": [],
      "created": "2 Sept 2025, 6:34 am",
      "id": "n0HTKhJqE59YliD19ZMe",
      "content": "The 4th International Conference on Applied Mathematics in Science and Engineering (AMSE-2025) was co-organized by Prof. Ram Prakash Sharma, Dept. of Mechanical Engineering, NIT Arunachal Pradesh, in collaboration with Siksha ‘O’ Anusandhan (Deemed to be University), ITER, Bhubaneswar, Odisha. The conference was held during August 28–30, 2025, at ITER, Siksha ‘O’ Anusandhan University, Bhubaneswar, Odisha, and was co-sponsored by NIT Arunachal Pradesh, India. "
    },
    "86IWn5bFmUwEcJGPAhmC": {
      "created": "2 Sept 2025, 6:45 am",
      "brochureUrl": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "imgCaption": "",
      "imgUrl": [],
      "title": "",
      "eventDate": "2025-09-11",
      "categoryId": "2",
      "approved": true,
      "author": "Ram Prakash Sharma",
      "createdInSeconds": 1756775737334,
      "id": "86IWn5bFmUwEcJGPAhmC",
      "content": "Prof. R. P. Sharma, Department of Mechanical Engineering, NIT Arunachal Pradesh, delivered a lecture titled “Recent Progress and Emerging Trends in Nanofluids Research” on Day 3 (Saturday, August 30, 2025) during the 1st Technical Session of the 4th International Conference on Applied Mathematics in Science and Engineering (AMSE-2025), held at ITER, Siksha ‘O’ Anusandhan University, Bhubaneswar, Odisha."
    },
    "1quF6ShQ8Js6JTggSsNq": {
      "approved": true,
      "eventDate": "2025-09-22",
      "imgUrl": [],
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "author": "Ram Prakash Sharma",
      "imgCaption": "",
      "created": "2 Sept 2025, 7:54 am",
      "categoryId": "16",
      "createdInSeconds": 1756779871821,
      "title": "",
      "brochureUrl": "",
      "id": "1quF6ShQ8Js6JTggSsNq",
      "content": "Mr. Abhishek Sharma, a PhD scholar in the Department of Basic and Applied Science, under the supervision of Prof. Ram Prakash Sharma, has been shortlisted as a Springer Nature Research Ambassador for Year 2025."
    },
    "r1wEVheXe4aQrCvlkWfD": {
      "approved": true,
      "eventDate": "2025-09-30",
      "title": "",
      "author": "Ram Prakash Sharma",
      "brochureUrl": "",
      "imgCaption": "Mr. Vinay Kumar V received the certificate for paper presentation.",
      "categoryId": "16",
      "created": "2 Sept 2025, 8:09 am",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "createdInSeconds": 1756780744842,
      "imgUrl": [],
      "id": "r1wEVheXe4aQrCvlkWfD",
      "content": "Vinay Kumar V, under the supervision of Prof. Ram Prakash Sharma, presented a paper entitled “Soret and Dufour Effects on Fluid Flow in Rotating Converging–Diverging Channels” at the 4th International Conference on Applied Mathematics in Science and Engineering (AMSE-2025), ITER, Siksha ‘O’ Anusandhan University, Bhubaneswar, Odisha, India, August 28–30, 2025."
    },
    "9NtPuEIXHmJgYgm1wUk2": {
      "approved": true,
      "imgUrl": [],
      "categoryId": "16",
      "createdInSeconds": 1756781355745,
      "title": "",
      "created": "2 Sept 2025, 8:19 am",
      "eventDate": "2025-09-23",
      "imgCaption": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "brochureUrl": "",
      "author": "Ram Prakash Sharma",
      "id": "9NtPuEIXHmJgYgm1wUk2",
      "content": "Dr. Laxmipriya Swain, under the supervision of Prof. Ram Prakash Sharma, presented a paper entitled “Time-Dependent Flow of Radiative Water-Based Carbon Nanotube Hybrid Nanofluid over a Stagnation Point Embedding Porous Matrix” at the 4th International Conference on Applied Mathematics in Science and Engineering (AMSE-2025), ITER, Siksha ‘O’ Anusandhan University, Bhubaneswar, Odisha, India, August 28–30, 2025."
    },
    "cOa31pHng7Nfvu5BLSUc": {
      "created": "2 Sept 2025, 8:20 am",
      "approved": true,
      "author": "Ram Prakash Sharma",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "title": "",
      "createdInSeconds": 1756781436775,
      "imgCaption": "Mr. Abhishek Sharma received the certificate for paper presentation.",
      "categoryId": "16",
      "brochureUrl": "",
      "imgUrl": [],
      "eventDate": "2025-10-01",
      "id": "cOa31pHng7Nfvu5BLSUc",
      "content": "Mr. Abhishek Sharma, under the supervision of Prof. Ram Prakash Sharma, presented a paper entitled “Thermal Efficiency Analysis of Second-Grade Nanofluids over Riga Plate Using an Implicit Finite Difference Approach” at the 4th International Conference on Applied Mathematics in Science and Engineering (AMSE-2025), ITER, Siksha ‘O’ Anusandhan University, Bhubaneswar, Odisha, India, August 28–30, 2025."
    },
    "zhAemnVpt1BFQvqDsHFJ": {
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "imgUrl": [],
      "categoryId": "16",
      "title": "",
      "author": "Ram Prakash Sharma",
      "imgCaption": "Chandralekha Mahanta received the certificate for paper presentation.",
      "createdInSeconds": 1756781531938,
      "created": "2 Sept 2025, 8:22 am",
      "approved": true,
      "eventDate": "2025-09-24",
      "brochureUrl": "",
      "id": "zhAemnVpt1BFQvqDsHFJ",
      "content": "Ms. Chandralekha Mahanta, under the supervision of Prof. Ram Prakash Sharma, presented a paper entitled “Analysis of Radiative MHD Nanofluid Flow over Cylindrical Surfaces in Porous Media for Energy-Efficient Thermal Systems” at the 4th International Conference on Applied Mathematics in Science and Engineering (AMSE-2025), ITER, Siksha ‘O’ Anusandhan University, Bhubaneswar, Odisha, India, August 28–30, 2025."
    },
    "EIKjqKdRficep8HIotBJ": {
      "eventDate": "2025-09-24",
      "createdInSeconds": 1756781749795,
      "created": "2 Sept 2025, 8:25 am",
      "imgUrl": [],
      "approved": true,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "title": "",
      "brochureUrl": "",
      "author": "Ram Prakash Sharma",
      "categoryId": "16",
      "imgCaption": "Mr. Bimal Kumar Barik received the certificate for paper presentation.",
      "id": "EIKjqKdRficep8HIotBJ",
      "content": "Mr. Bimal Kumar Barik, under the supervision of Prof. Ram Prakash Sharma, presented a paper entitled “Machine Learning-Based Physics-Informed Neural Network Modeling of Bioconvective Nanofluid Flow over a Stretching Sheet” at the 4th International Conference on Applied Mathematics in Science and Engineering (AMSE-2025), ITER, Siksha ‘O’ Anusandhan University, Bhubaneswar, Odisha, India, August 28–30, 2025."
    },
    "eK3bcTcbob2CnaHnmD6W": {
      "categoryId": "16",
      "created": "2 Sept 2025, 8:35 am",
      "createdInSeconds": 1756782344055,
      "approved": true,
      "imgCaption": "Photo with Prof. J. V. Ramanamurthy, Department of Mathematics, NIT Warangal (Ph.D. Thesis Defense Examiner), Prof SR Mishra, Dept of Mathematics, SOA University, Odisha and Prof. BC Prasannakumara, Dept. of Mathematics, Davangere University, Karnataka   ",
      "eventDate": "2025-09-11",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "author": "Ram Prakash Sharma",
      "brochureUrl": "",
      "imgUrl": [],
      "title": "",
      "id": "eK3bcTcbob2CnaHnmD6W",
      "content": "Ms. Laxmipriya Swain successfully defended her Ph.D. thesis entitled “Enhancing Heat Transfer Efficiency through Nanofluid Application” under the supervision of Prof. Ram Prakash Sharma, at the Department of Basic and Applied Sciences, NIT Arunachal Pradesh, on August 8, 2025. The defense was held in the Mechanical Engineering Department Conference Hall."
    },
    "S66nw7yXPEtxun7zKSoR": {
      "categoryId": "16",
      "approved": true,
      "title": "",
      "author": "Ram Prakash Sharma",
      "imgUrl": [],
      "createdInSeconds": 1756791959463,
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "eventDate": "2025-10-01",
      "created": "2 Sept 2025, 11:15 am",
      "imgCaption": "",
      "brochureUrl": "",
      "id": "S66nw7yXPEtxun7zKSoR",
      "content": "Mr. Vinay Kumar V and Mr. Abhishek Sharma, PhD scholars from the Department of Basic and Applied Science, NIT Arunachal Pradesh, visited the Department of Mathematics, Rajiv Gandhi University, Arunachal Pradesh, to explore possible research collaboration with Prof. Sahin Ahmed."
    },
    "WgOQJXc4EHolsiLAuwn0": {
      "brochureUrl": "",
      "eventDate": "2025-09-18",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "imgCaption": "",
      "author": "Ram Prakash Sharma",
      "title": "",
      "approved": true,
      "createdInSeconds": 1756866465633,
      "categoryId": "2",
      "created": "3 Sept 2025, 7:57 am",
      "imgUrl": [],
      "id": "WgOQJXc4EHolsiLAuwn0",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering, NITAP delivered an invited  Talk on \" Success of Secrete: Strategies for Life” on  July 24, 2025, organized by Ramakrishna Mission Ashrama, Sohra (Cherrapunjee) PO Sohra, Dt. East Khasi Hills, Meghalaya 793 108, India 94363 10959 sohra@rkmm.org"
    },
    "sYLSlNALVVLUMWLdLW0b": {
      "author": "Ram Prakash Sharma",
      "title": "",
      "eventDate": "2025-09-15",
      "approved": true,
      "created": "3 Sept 2025, 8:00 am",
      "brochureUrl": "",
      "imgCaption": "",
      "createdInSeconds": 1756866611410,
      "imgUrl": [],
      "categoryId": "2",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "id": "sYLSlNALVVLUMWLdLW0b",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering, NITAP delivered a Talk on Blueprint for Greatness on the Occasion of Guru Poornima Celebration on July 23, 2025, organized by the NIT Meghalaya."
    },
    "y70mkaqCWhrALlJiCbYH": {
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "eventDate": "2025-09-15",
      "author": "Ram Prakash Sharma",
      "categoryId": "3",
      "imgUrl": [],
      "title": "",
      "brochureUrl": "",
      "approved": true,
      "createdInSeconds": 1756866805693,
      "created": "3 Sept 2025, 8:03 am",
      "imgCaption": "",
      "id": "y70mkaqCWhrALlJiCbYH",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering, NITAP delivered a Talk on How to write and published research papers in very good Journals on July 23, 2025, organized by the Department of Mechanical Engineering, NIT Meghalaya."
    },
    "EmbfpLbBhc0mN3BRc3Tm": {
      "categoryId": "2",
      "createdInSeconds": 1756866939032,
      "brochureUrl": "",
      "approved": true,
      "author": "Ram Prakash Sharma",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "title": "",
      "eventDate": "2025-09-16",
      "imgCaption": "",
      "imgUrl": [],
      "created": "3 Sept 2025, 8:05 am",
      "id": "EmbfpLbBhc0mN3BRc3Tm",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering, NITAP delivered an invited Talk on Greatest Secrete of Successes on the Occasion of Guru Poornima  Celebration on July 10, 2025, organized by the Department of Mechanical Engineering, Shahu College of Engineering, Pune, Maharashtra."
    },
    "4raivNfg77z8nQsRo8S6": {
      "imgUrl": [],
      "categoryId": "2",
      "approved": true,
      "createdInSeconds": 1756867032821,
      "created": "3 Sept 2025, 8:07 am",
      "eventDate": "2025-09-19",
      "author": "Ram Prakash Sharma",
      "title": "",
      "brochureUrl": "",
      "imgCaption": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "id": "4raivNfg77z8nQsRo8S6",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering, NITAP delivered a Talk on \" Greatest Secrete of Successes \" in the Keynote Speaker and chief guest on the Occasion of Guru Poornima  Celebration on July 10, 2025, organized by D Y Patil University, Pune, Maharashtra."
    },
    "V6vULfL3a4ceAi12HF94": {
      "createdInSeconds": 1756878937566,
      "title": "",
      "eventDate": "2025-09-18",
      "categoryId": "16",
      "created": "3 Sept 2025, 11:25 am",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "approved": true,
      "author": "Ram Prakash Sharma",
      "imgCaption": "",
      "imgUrl": [],
      "brochureUrl": "",
      "id": "V6vULfL3a4ceAi12HF94",
      "content": "Ram Prakash Sharma visited Lab. Department of Chemistry, SPP University Pune and interaction with students, Also meeting with Prof . (DR.) Geeta Sharma and Prof. (Dr.) Santosh Terdale on 9th July 2025"
    },
    "M1PXW3uAtvaDIwvFOxMP": {
      "imgUrl": [],
      "categoryId": "16",
      "approved": true,
      "brochureUrl": "",
      "createdInSeconds": 1756879054047,
      "author": "Ram Prakash Sharma",
      "created": "3 Sept 2025, 11:27 am",
      "imgCaption": "",
      "title": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "eventDate": "2025-09-23",
      "id": "M1PXW3uAtvaDIwvFOxMP",
      "content": "Ram Prakash Sharma visited Lab of Department of Mechanical Engineering and meeting with faculty members, with Head of School Prof. (Dr.) K. B. Sutar, Professor & HOD, Department of Mechanical Engineering, Bharatiya Vidyapeeth (Deemed To Be University) College of Engineering Pune on 4th July 2025. "
    },
    "L1xnwfIBcqlmLJMEnXXe": {
      "approved": true,
      "categoryId": "12",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "eventDate": "2025-09-25",
      "title": "",
      "imgUrl": [],
      "imgCaption": "",
      "author": "Ram Prakash Sharma",
      "brochureUrl": "",
      "createdInSeconds": 1756880308684,
      "created": "3 Sept 2025, 11:48 am",
      "id": "L1xnwfIBcqlmLJMEnXXe",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering, served as a Thesis Reviewer for the Mathematics Department, of thesis entitled “A study on some topological properties in minuscule topological spaces with computational approach to open sets using Python and Java”, submitted by Purushoth Kumar S., in the PG Department of Mathematics, University of Madras, Chepauk, Chennai- 600005, Chennai (India), under supervision of Dr. R. Alagar, Associate Professor, PG Department of Mathematics, Rajeswari Vedachalam Government Arts College, Chengalpattu- 603001, Chennai (India)."
    },
    "YpzVslUuNdCj6yrIltiH": {
      "eventDate": "2025-09-19",
      "imgCaption": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "imgUrl": [],
      "author": "Ram Prakash Sharma",
      "brochureUrl": "",
      "approved": true,
      "categoryId": "12",
      "created": "3 Sept 2025, 11:49 am",
      "createdInSeconds": 1756880396661,
      "title": "",
      "id": "YpzVslUuNdCj6yrIltiH",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering, served as a Thesis Reviewer for the Mathematics Department, of thesis entitled “Construction of labeled graphs and digraphs using algebraic structures”, submitted by Ancy Caroline Dsouza (USN: 4NM19PMA01), in the Department of Mathematics, N.M.A.M. Institute of Technology, NITTE- 574110 under Visvesvaraya Technological University, Belagavi- 590018, Karnataka (India), under supervision of Dr. Kumudakshi, Associate Professor, Department of Mathematics, N.M.A.M. Institute of Technology, Nitte- 574110 under Visvesvaraya Technological University, Belagavi- 590018, Karnataka (India)."
    },
    "hbvAt7Y9vEH3sybGzysg": {
      "brochureUrl": "",
      "title": "",
      "eventDate": "2025-09-12",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "imgUrl": [],
      "categoryId": "12",
      "approved": true,
      "created": "3 Sept 2025, 11:50 am",
      "author": "Ram Prakash Sharma",
      "createdInSeconds": 1756880448005,
      "imgCaption": "",
      "id": "hbvAt7Y9vEH3sybGzysg",
      "content": "Prof. Ram Prakash Sharma, Professor, Department of Mechanical Engineering, served as a Thesis Reviewer for the Mathematics Department, of thesis entitled “Multilayer heat transport in nanoliquids with sensitivity analysis”, submitted by Shruthy Myson, in the Department of Mathematics, School of sciences, Christ (Deemed to be University), Bengaluru- 560029, Karnataka (India), under supervision of Dr. Mahanthesh B., Associate Professor, Department of Mathematics, School of sciences, Christ (Deemed to be University), Bengaluru- 560029, Karnataka (India)."
    },
    "1bRND49PRZsQAYPTolmP": {
      "categoryId": "16",
      "imgUrl": [],
      "brochureUrl": "",
      "title": "",
      "created": "3 Sept 2025, 11:53 am",
      "imgCaption": "",
      "uid": "X9dcSlcjamVcZ5OpJ2bbASQWfMH2",
      "eventDate": "2025-09-08",
      "author": "Ram Prakash Sharma",
      "approved": true,
      "createdInSeconds": 1756880591812,
      "id": "1bRND49PRZsQAYPTolmP",
      "content": "Ram Prakash Sharma organized two lectures, two eminent speakers Prof. B C Prasannakumara and Prof. S R Mishra delivered a lecture for faculty members, PG Students and PhD scholars today i.e., on 11-08-2025 at Second floor Mechanical block."
    }
  },
  "subSections": {
    "1": {
      "id": "1",
      "title": "Memorandum of Understanding (MoU)",
      "activityIds": [
        "Y8ARm0JBVZ64qcYuM7Sd"
      ]
    },
    "2": {
      "id": "2",
      "title": "Invited/Expert Lectures given by NIT AP members",
      "activityIds": [
        "86IWn5bFmUwEcJGPAhmC",
        "WgOQJXc4EHolsiLAuwn0",
        "sYLSlNALVVLUMWLdLW0b",
        "EmbfpLbBhc0mN3BRc3Tm",
        "4raivNfg77z8nQsRo8S6"
      ]
    },
    "3": {
      "id": "3",
      "title": "Visits and Invited/Expert Lectures to NITAP from other insitutes",
      "activityIds": [
        "hp8RVGK1d1wM4UQI51rx",
        "y70mkaqCWhrALlJiCbYH"
      ]
    },
    "6": {
      "id": "6",
      "title": "Patent",
      "activityIds": [
        "9CqWdNqfXUvHMnTF0VuQ"
      ]
    },
    "7": {
      "id": "7",
      "title": "Research Papers",
      "activityIds": [
        "C5n9IvzZrShJYqPhbdyc",
        "vf32dOPSIVtfukL4xiiP",
        "bup9d1qro73Ql65Cmiu7",
        "vDVpvrWDC8GfLKYgBZJS",
        "U6rK5uZ0VtMaFkj3G7Yu",
        "nYaCeKa0yoLfU3YUY09a",
        "fsZQU2Tkl0QQ4LRPA6Mz",
        "BoiAu0mlstrDFlmqtdA2",
        "HnNGcVRRzU3kqUplIqML",
        "2cHZuff6IG5NinpPGIhu",
        "Ii4pBcRdx5MbGFnWHkVS",
        "ht1IPMCjYNaIwZyCPHvB",
        "xvMpWY0OHsLORnL2UwtK",
        "GLUyZVgQJZ8UqGTEPipl",
        "o5C8ZUZxAWvGhZcm2BTy",
        "REzD7ncwKwQRUcfCpXnP",
        "xjJygvcamjtjRXKMbIE2",
        "BFy9JhileGbXfQPLhSEU",
        "X49gQEmeN6EAgyGAwdoI",
        "suI6i9hG4Pgmxn6CkGpx",
        "4FMGmDnF3mSyPpFMGRTR",
        "Aj7baiJTWXqmzhzSpR7R",
        "xjuaEyN49VYXPSanCNa2",
        "ttYkfIRXoVfsOC6Bo87U",
        "wAbUuKu19grnTvb4PHW7",
        "6Qp38c78JlIDrnm0wkmI"
      ]
    },
    "9": {
      "id": "9",
      "title": "Conference Papers",
      "activityIds": [
        "z7iVjJbODcKCzkrioQlY",
        "RDYeVPDDquAQFl3HhPR1",
        "RmBzNnhsWCWW7Z77RtX6"
      ]
    },
    "10": {
      "id": "10",
      "title": "Book Chapters",
      "activityIds": [
        "S0tnvVYW05gjvMatzlUT"
      ]
    },
    "11": {
      "id": "11",
      "title": "Faculty Empowerment Programmes",
      "activityIds": [
        "nZRRViBM2XshsLRnIOqu",
        "uSX9PNjIslgijdKts2Lf"
      ]
    },
    "12": {
      "id": "12",
      "title": "Reviewers",
      "activityIds": [
        "hlGPiuzkGKjdFanqbel9",
        "76qWVFxriWGPOZv37qVG",
        "NU1ITQdp1OXnHHhweteZ",
        "L8pzluz3a8NVkoobkPqx",
        "Z7XdEZJoKNPrfWPdDmA2",
        "CREqTN91Rzmwap0Ro7ni",
        "w1SHbJn4UR3yeO8KBjwH",
        "doWW0zGvS72f5eX0LebO",
        "sFn5fHs8SmeoL5btXZ0V",
        "rpZd3SUipz3ToVHZGS1g",
        "gvET66KrcpBmwQdWkKDF",
        "BrY8Ye12o34Q9M0MZXqx",
        "NNUhY2EnPOtoPw0yQfyt",
        "Dz5tUqhnMJfGUp7Xi03Z",
        "FGGTSNsa7Af7wUF4rseg",
        "bNowasf5NIi7vBPvqBmJ",
        "JNpI9mBGsg65KVhfu2PL",
        "A8lHJhoaOpe3JOKG6nSE",
        "BobZCSgH2CEqN3HNnkBm",
        "AtGgSUk2C8wjMuBNBF5e",
        "7D7t32uvCuTbnWlv39Cu",
        "U4kbLiytOGxPs1KgbHyd",
        "8uw5mXDWH1AqzMF1KQnM",
        "SSbYCL7fF20tufMoxCHJ",
        "DLJlPmC9yYCMCpeXcFkI",
        "j1jeDEFzLDFnNAoFe0cT",
        "l8HBLJX09V0tGaTYhmmg",
        "riSMQRqVfL03Wh2Gr0II",
        "S4LNioAr93ojP5nLEhks",
        "L1xnwfIBcqlmLJMEnXXe",
        "YpzVslUuNdCj6yrIltiH",
        "hbvAt7Y9vEH3sybGzysg"
      ]
    },
    "13": {
      "id": "13",
      "title": "Session Chairs",
      "activityIds": [
        "k261H9AhjILUU0G51mQQ"
      ]
    },
    "14": {
      "id": "14",
      "title": "Winners of Competition",
      "activityIds": [
        "3UxlNWKfXTKU0D3mZ8Xu",
        "6o2v6oRuDOwAuPoBWcWD",
        "z7KpekfOIDx872AcJg2D",
        "3oDE0a118HDks0pK3jNx",
        "fuUASgPTwEJEZR4rKE2P",
        "ogcoQMsp38hydeiUVdpY",
        "OCqsmeTb9QjfBu5bBN2f",
        "3ZegLm5nSYPWgSzmrDCL",
        "Uan444PjT9Ggh6VG2sDf"
      ]
    },
    "15": {
      "id": "15",
      "title": "Workshop / FDP / Conference / seminar / short term course etc.",
      "activityIds": [
        "ZrdhBGA2YaxjOZeWqViq",
        "KiLungNO3KWEPwo0eOlN",
        "n0HTKhJqE59YliD19ZMe"
      ]
    },
    "16": {
      "id": "16",
      "title": "Outreach Activity",
      "activityIds": [
        "EABXjZhJ0XiBHOXVMOsL",
        "xEgHUg3ZRibY7NBaCeUR",
        "1quF6ShQ8Js6JTggSsNq",
        "r1wEVheXe4aQrCvlkWfD",
        "9NtPuEIXHmJgYgm1wUk2",
        "cOa31pHng7Nfvu5BLSUc",
        "zhAemnVpt1BFQvqDsHFJ",
        "EIKjqKdRficep8HIotBJ",
        "eK3bcTcbob2CnaHnmD6W",
        "S66nw7yXPEtxun7zKSoR",
        "V6vULfL3a4ceAi12HF94",
        "M1PXW3uAtvaDIwvFOxMP",
        "1bRND49PRZsQAYPTolmP"
      ]
    }
  }
}
